' GENERATED by scratchpad opaque-fo4/impl/gen_fo4_sources.py: do not edit the GLSL by hand.
''' <summary>THE D3D11 INSTRUCTION SEMANTICS GLSL LEAVES UNDEFINED (min/max with NaN, _sat, div, sqrt, rsq, log, exp, ftoi), ONE copy
''' for every shader transcribed from Direct3D bytecode in both games (SSE SAO passes and SAO normals, FO4 G-buffer, lights and
''' composite). ASCII only (GLSL).</summary>
Friend Module D3d11SemanticsSource
    Friend Const Glsl As String = "// ONE copy for every transcribed shader of both games (SSE SAO / SAO normals, FO4 G-buffer / lights / composite).
#define D3D_NEG_INF   uintBitsToFloat(0xFF800000u)
#define D3D_POS_INF   uintBitsToFloat(0x7F800000u)
#define D3D_QNAN      uintBitsToFloat(0x7FC00000u)

// D3D11 min/max: if exactly one operand is NaN the other one is returned (GLSL min/max leave it undefined).
float d3d_min(float a, float b) { return isnan(a) ? b : (isnan(b) ? a : min(a, b)); }
float d3d_max(float a, float b) { return isnan(a) ? b : (isnan(b) ? a : max(a, b)); }

// D3D11 _sat: clamp to [0,1], NaN -> 0.
float d3d_sat(float x) { return (x > 0.0) ? ((x < 1.0) ? x : 1.0) : 0.0; }

// D3D11 div (IEEE): x/0 = +-inf with the XOR of the signs, 0/0 = NaN, inf/inf = NaN (GLSL leaves x/0 unspecified).
float d3d_div(float a, float b)
{
    if (isnan(a) || isnan(b)) return D3D_QNAN;
    if (b == 0.0)
    {
        if (a == 0.0) return D3D_QNAN;
        bool neg = ((floatBitsToUint(a) ^ floatBitsToUint(b)) & 0x80000000u) != 0u;
        return neg ? D3D_NEG_INF : D3D_POS_INF;
    }
    if (isinf(a) && isinf(b)) return D3D_QNAN;
    return a / b;
}

// D3D11 sqrt: sqrt(x<0) = NaN, sqrt(-0) = -0, sqrt(+inf) = +inf (GLSL sqrt(x<0) is undefined).
float d3d_sqrt(float x)
{
    if (isnan(x) || x < 0.0) return D3D_QNAN;
    return sqrt(x);
}

// D3D11 rsq: rsq(x<0) = NaN, rsq(+0) = +inf, rsq(-0) = -inf, rsq(+inf) = 0 (GLSL inversesqrt(x<=0) is undefined).
float d3d_rsq(float x)
{
    if (isnan(x) || x < 0.0) return D3D_QNAN;
    if (x == 0.0) return ((floatBitsToUint(x) & 0x80000000u) != 0u) ? D3D_NEG_INF : D3D_POS_INF;
    if (isinf(x)) return 0.0;
    return inversesqrt(x);
}

// D3D11 log (base 2): log(+-0) = -inf, log(x<0) = NaN (GLSL log2(x<=0) is undefined).
float d3d_log2(float x)
{
    if (isnan(x) || x < 0.0) return D3D_QNAN;
    if (x == 0.0) return D3D_NEG_INF;
    return log2(x);
}

// D3D11 exp (base 2): exp(-inf) = 0.
float d3d_exp2(float x)
{
    if (isinf(x) && x < 0.0) return 0.0;
    return exp2(x);
}

// SSE SAO extras (same D3D11 rules): vector min/max and ftoi.
vec2 d3d_min(vec2 a, vec2 b) { return vec2(d3d_min(a.x, b.x), d3d_min(a.y, b.y)); }
vec2 d3d_max(vec2 a, vec2 b) { return vec2(d3d_max(a.x, b.x), d3d_max(a.y, b.y)); }
vec4 d3d_min(vec4 a, vec4 b) { return vec4(d3d_min(a.xy, b.xy), d3d_min(a.zw, b.zw)); }
vec4 d3d_max(vec4 a, vec4 b) { return vec4(d3d_max(a.xy, b.xy), d3d_max(a.zw, b.zw)); }
// D3D11 ftoi: round toward zero; NaN -> 0; >= 2^31 -> INT_MAX; <= -2^31 -> INT_MIN (GLSL int() is undefined there).
int d3d_ftoi(float x)
{
    if (isnan(x)) return 0;
    if (x >= 2147483648.0) return int(0x7FFFFFFFu);
    if (x <= -2147483648.0) return int(0x80000000u);
    return int(x);
}

// D3D11 ld (load without sampler): an address outside the mip's extent, or a mip outside the resource, returns 0 in every
// component (D3D11.3 functional specification, the ld instruction); GLSL texelFetch is undefined there.
vec4 d3d_ld2d(sampler2D t, ivec2 p, int lod)
{
    if (lod < 0 || lod >= textureQueryLevels(t)) return vec4(0.0);
    ivec2 s = textureSize(t, lod);
    if (any(lessThan(p, ivec2(0))) || any(greaterThanEqual(p, s))) return vec4(0.0);
    return texelFetch(t, p, lod);
}
"
End Module
