' GENERATED by scratchpad opaque-fo4/impl/gen_fo4_sources.py from opaque-fo4/transcripcion/Fo4DeferredSource.glsl.txt.
''' <summary>FALLOUT 4 DEFERRED LIGHTS AND COMPOSITE (BSDFLight b10, BSDFComposite b11) transcribed from the bytecode line by line
''' (Tools/re-docs/RE_FO4_DEFERRED_FRAME_2026-10-03.md, RE_FO4_WORLD_ENVMAP_2026-10-03.md). The app's deviations from the
''' transcribed text, each with its reason and its mutant in ShadowGate --fo4-deferred-law:
''' <para>DFLight3323 l.62: rig fill = directional light: L constant (D)</para>
''' <para>DFLight3323 fill shadow: fill shadow factor multiplies o0/o1 (rev-21 b)</para>
''' <para>DFLight3323 shadow uniforms: fill shadow inputs</para>
''' <para>DFComposite3495 SV_Position: composite 2 in LOWER_LEFT: SV_Position = (x, H - y) (A.5)</para>
''' <para>DFComposite3495 coverage: coverage output and viewport height (rev-19, A.5)</para>
''' <para>DFComposite3495 coverage write: coverage = 1 on every composited pixel, right after line 50 (rev-19; 3495 has no discard and one ret)</para>
''' ASCII only (GLSL).</summary>
Friend Module Fo4DeferredSource
    Friend Const Header430 As String = "#version 430
"

    Friend Const Header430Deriv As String = "#version 430
#extension GL_ARB_derivative_control : require
"

    Friend Const Prelude As String = "// ---------------------------------------------------------------------------------------------------------------------
// CONVENTION (FO4 deferred transcription)
//  * Every pass runs under glClipControl(GL_UPPER_LEFT, GL_NEGATIVE_ONE_TO_ONE) (ARB_clip_control, core in GL 4.5).
//    UPPER_LEFT only negates NDC y; window coordinates keep their definition. So clip y = +1 lands in window row 0 =
//    memory row 0, where D3D puts NDC y = +1 (render-target row 0): gl_FragCoord.xy == SV_Position.xy, the window y
//    grows down the image like D3D's screen y (dFdyCoarse == deriv_rty_coarse, no sign change; 2x2 quads pair the
//    same rows), and every texture written under UPPER_LEFT is sampled with the D3D uv directly.
//  * Inputs: the G-buffer (RT 0x1A/0x1B/0x1D/0x1E/0x1F), the depth-stencil, the light targets (RT 0x21/0x22), RT 2,
//    the linear depth t15 and the app shadow factor MUST be in D3D row order, i.e. rendered under the same UPPER_LEFT
//    state. Reason: the light/composite passes depth-test against the G-buffer depth (GEQUAL / GREATER), which only
//    works if the depth attachment has the same row order as the pass, and the SSS taps of pass 2 read t3/t10/t15 at
//    uv that are NOT texel centres (a (u, 1-v) flip is exact only at texel centres). If an input is LOWER_LEFT anyway,
//    its exact flip is t = (u, 1 - v) at texel centres only; see notas.md D2.
//  * View space: engine view space is x right, y up, +z forward (ENV 9.1: projection M[2][3] = 1 => w_clip = +z_view).
//    The app's GL view space is x right, y up, -z forward: v_engine = (v_gl.x, v_gl.y, -v_gl.z) for positions,
//    normals and light vectors. The G-buffer normal is the engine encode of n_engine with n.z <= 0 (DF 6):
//        t1.xy = n_e.xy / sqrt(8 - 8 n_e.z) + 0.5      (R16G16_UNORM)
//    so the decode below (asm 3321:65..70) is transcribed as is.
//  * Depth: D3D window depth d in [0,1]. GL with glDepthRange(0,1) and NDC z in [-1,1] stores the same d for the same
//    D3D clip position if the VS emits z_gl = 2 z_d3d - w (VS_DFLIGHT / VS_DFCOMPOSITE do exactly that).
//  * Literals: the exact 32-bit token of the SHEX chunk (lits.py / litmap.py, per line: litmap_<rec>.txt). Every
//    non-dyadic literal is a macro NAME uintBitsToFloat(0x........u), printed decimal in the comment. A macro and not
//    a const: glslang rejects uintBitsToFloat in a global const initializer.
//  * D3D11 semantics GLSL does not guarantee are the helpers below (same names and law as the SSE SAO transcription
//    PRELUDE; when wired into the app both must be one shared include).
// ---------------------------------------------------------------------------------------------------------------------


// --- literal tokens (printed decimal -> token). Dyadic literals (0.25, 0.5, 1, 2, 3, 4, 5, 6, 10, 15, 50, 100, 255,
//     0.0625, 0.078125) are exact in decimal and written inline.
#define FO4_L_0_01        uintBitsToFloat(0x3C23D70Au)   // l(0.010000)
#define FO4_L_M0_01       uintBitsToFloat(0xBC23D70Au)   // l(-0.010000)
#define FO4_L_1_01        uintBitsToFloat(0x3F8147AEu)   // l(1.010000)
#define FO4_L_M0_98       uintBitsToFloat(0xBF7AE148u)   // l(-0.980000)
#define FO4_L_0_57        uintBitsToFloat(0x3F11EB85u)   // l(0.570000)
#define FO4_L_0_09        uintBitsToFloat(0x3DB851ECu)   // l(0.090000)
#define FO4_L_0_45        uintBitsToFloat(0x3EE66666u)   // l(0.450000)
#define FO4_L_INV_2PI     uintBitsToFloat(0x3E22F983u)   // l(0.159155)  token != float(0.159155) = 0x3E22F987
#define FO4_L_2POW_M23    uintBitsToFloat(0x34000000u)   // l(0.000000)  !! token is 2^-23 = 1.1920929e-7, NOT zero
#define FO4_L_0_2         uintBitsToFloat(0x3E4CCCCDu)   // l(0.200000)
#define FO4_L_PI          uintBitsToFloat(0x40490FDBu)   // l(3.141593)  token != float(3.141593) = 0x40490FDC
#define FO4_L_ONE_THIRD   uintBitsToFloat(0x3EAAAAABu)   // l(0.333333)  token != float(0.333333) = 0x3EAAAA9F
#define FO4_L_2_2         uintBitsToFloat(0x400CCCCDu)   // l(2.200000)
#define FO4_L_0_001       uintBitsToFloat(0x3A83126Fu)   // l(0.001000)
#define FO4_L_0_001961    uintBitsToFloat(0x3B008081u)   // l(0.001961)  token = 1/255 + ..., != float(0.001961)
#define FO4_L_1_512       uintBitsToFloat(0x3B000000u)   // l(0.001953)  token = 1/512, != float(0.001953)
#define FO4_L_LUMA_R      uintBitsToFloat(0x3E991687u)   // l(0.299000)
#define FO4_L_LUMA_G      uintBitsToFloat(0x3F1645A2u)   // l(0.587000)
#define FO4_L_LUMA_B      uintBitsToFloat(0x3DE978D5u)   // l(0.114000)
#define FO4_L_0_9         uintBitsToFloat(0x3F666666u)   // l(0.900000)
#define FO4_L_0_13889     uintBitsToFloat(0x3E0E392Eu)   // l(0.138890)
#define FO4_L_M1_28       uintBitsToFloat(0xBFA3D70Au)   // l(-1.280000)
#define FO4_L_1_28        uintBitsToFloat(0x3FA3D70Au)   // l(1.280000)
#define FO4_L_M0_72       uintBitsToFloat(0xBF3851ECu)   // l(-0.720000)
#define FO4_L_0_72        uintBitsToFloat(0x3F3851ECu)   // l(0.720000)
#define FO4_L_M0_32       uintBitsToFloat(0xBEA3D70Au)   // l(-0.320000)
#define FO4_L_0_32        uintBitsToFloat(0x3EA3D70Au)   // l(0.320000)
#define FO4_L_M0_08       uintBitsToFloat(0xBDA3D70Au)   // l(-0.080000)
#define FO4_L_0_08        uintBitsToFloat(0x3DA3D70Au)   // l(0.080000)
#define FO4_L_0_1         uintBitsToFloat(0x3DCCCCCDu)   // l(0.100000)
#define FO4_L_M0_3        uintBitsToFloat(0xBE99999Au)   // l(-0.300000)
// SSS weights (rec3495; R, G, B). Several printed decimals are not the token; the +-2 taps are NOT symmetric in B.
#define FO4_W_SSS_0       vec3(uintBitsToFloat(0x3F0F7B8Du), uintBitsToFloat(0x3F2B4938u), uintBitsToFloat(0x3F48E3EFu)) // 136: 0.560479 0.669086 0.784728
#define FO4_W_SSS_008     vec3(uintBitsToFloat(0x3D9E10A7u), uintBitsToFloat(0x3DE86DF8u), uintBitsToFloat(0x3DA29224u)) // 202,218: 0.077180 0.113491 0.079380
#define FO4_W_SSS_032     vec3(uintBitsToFloat(0x3DA85371u), uintBitsToFloat(0x3D12E2C6u), uintBitsToFloat(0x3CAB6D36u)) // 185,235: 0.082190 0.035861 0.020926
#define FO4_W_SSS_072     vec3(uintBitsToFloat(0x3D150DAEu), uintBitsToFloat(0x3C56A0F7u), uintBitsToFloat(0x3BD2EC36u)) // 169,251: 0.036390 0.013100 0.006437
#define FO4_W_SSS_128     vec3(uintBitsToFloat(0x3C9DF797u), uintBitsToFloat(0x3B38D2C5u), uintBitsToFloat(0x3A5CC30Fu)) // 152,268: 0.019283 0.002820 0.000842
#define FO4_W_SSS_M2      vec3(uintBitsToFloat(0x3B9A904Fu), uintBitsToFloat(0x3941BF16u), uintBitsToFloat(0x3854E37Cu)) // 135: 0.004717 0.000185 0.000051
#define FO4_W_SSS_P2      vec3(uintBitsToFloat(0x3B9A904Fu), uintBitsToFloat(0x3941BF16u), uintBitsToFloat(0x3854E360u)) // 283: 0.004717 0.000185 0.000051

"

    Friend Const Vs_Light As String = "// b10_DFLight_VS_rec3071_t00000000. Full-screen lights (sun, ambient): the engine draws the quad [DFLight+0x198]
// = 4 vertices (-1,1,0) (-1,-1,0) (1,-1,0) (1,1,0) (ctor 0x142246595..0x142246669) with WorldViewProj rows
// (1,0,0,0) (0,1,0,0) (0,0,1,zq) (0,0,0,1), zq = min(fl((f*f - f*n) / ((f - n) * f)), 0x3F7FFFFE) in float32
// (0x142247304..0x142247362, also 0x1422471B4..0x1422471EE and 0x14224751D..0x142247550). Point lights: the light
// volume mesh with its world*view*proj (D3D z in [0,w]). See notas.md section 3.
layout(location = 0) in vec3 v0;                // POSITION0 (asm 9: xyzw declared, xyz used; 22 dcl_input v0.xyz)
uniform vec4 WorldViewProj[4];                  // cb2[0..3] (rows as the cbuffer holds them: o.i = dot(cb2[i], v))
void main()
{
    vec4 r0, r1, o0;
    r0.xyz = v0.xyz;                            // 26  mov r0.xyz, v0.xyzx
    r0.w = 1.0;                                 // 27  mov r0.w, l(1.000000)
    r1.x = dot(WorldViewProj[2], r0);           // 28  dp4 r1.x, cb2[2].xyzw, r0.xyzw
    r1.y = dot(WorldViewProj[3], r0);           // 29  dp4 r1.y, cb2[3].xyzw, r0.xyzw
    o0.z = d3d_min(r1.y, r1.x);                 // 30  min o0.z, r1.y, r1.x
    o0.w = r1.y;                                // 31  mov o0.w, r1.y
    o0.x = dot(WorldViewProj[0], r0);           // 32  dp4 o0.x, cb2[0].xyzw, r0.xyzw
    o0.y = dot(WorldViewProj[1], r0);           // 33  dp4 o0.y, cb2[1].xyzw, r0.xyzw
    // 34  mov o1.xyzw, l(1,1,1,1): POSITION14, declared by the light PS but never read by them -> not emitted.
    // D3D clip z in [0, w] -> GL NEGATIVE_ONE_TO_ONE: same window depth d = z/w under glDepthRange(0,1).
    gl_Position = vec4(o0.x, o0.y, 2.0 * o0.z - o0.w, o0.w);
}
"

    Friend Const Vs_Composite As String = "// b11_DFComposite_VS_rec3378_t00000000. The engine draws the triangle (-1,1,1) (-1,-3,1) (3,1,1) (DF 4.4, ctor
// 0x142216600) => window depth 1.0 with test GREATER: pixels whose stored depth is 1.0 are not written.
layout(location = 0) in vec3 v0;                // POSITION0 (asm 20 dcl_input v0.xyz)
void main()
{
    vec4 o0;
    o0.xyz = v0.xyz;                            // 22  mov o0.xyz, v0.xyzx
    o0.w = 1.0;                                 // 23  mov o0.w, l(1.000000)
    gl_Position = vec4(o0.x, o0.y, 2.0 * o0.z - o0.w, o0.w);   // D3D z = 1 -> GL z_ndc = 1 -> window 1.0
}
"

    Friend Const Cb12 As String = "// cb12 (per-frame, written by 0x14181E1C0 at fixed offsets; no GetString table -> names are mine, content cited).
// Rows exactly as the cbuffer registers hold them.
uniform vec4 cb12_ViewToWorld[3];   // cb12[12..14]: transpose(inverse(view)) rows (ENV 3.2, 9.1): R_world.i = dot(.xyz, Rv)
uniform vec4 cb12_InvProj[4];       // cb12[20..23]: transpose(inverse(proj))   (ENV 8.1): p_i = dot(cb12[20+i], c)
uniform vec4 cb12_InvProj1P[4];     // cb12[24..27]: first-person range copy (cam+0x8A0, ENV 8.1), used when d <= 0.01
uniform vec4 cb12_HairSpec[2];      // cb12[28..29]: (0.02, 125, 1.2, 160), (0.36, -0.4, 0, 0)  (ENV 16.3)
uniform vec4 cb12_30;               // cb12[30]: .y = WorldRainLevel (ENV 14.1). Preview scope: no rain -> upload .y = 0
"

    Friend Const LightCommon As String = "// Resources of the light PS (BSDFLight binding 0x142248EAE..0x142248F02; sampler state 0x142248F07..0x142248FF2:
// slots 0..3 ADDR 0 (CLAMP) and FILT 0 (MIN_MAG_MIP_POINT, MaxLOD = MinLOD) -> GL: CLAMP_TO_EDGE, NEAREST/NEAREST,
// textures with BASE_LEVEL = MAX_LEVEL = 0).
layout(binding = 0) uniform sampler2D t0;       // RT 0x1A albedo, R8G8B8A8_UNORM_SRGB -> GL_SRGB8_ALPHA8 (decoded)
layout(binding = 1) uniform sampler2D t1;       // RT 0x1B normal, R16G16_UNORM -> GL_RG16
layout(binding = 2) uniform sampler2D t2;       // RT 0x1E (gloss, spec, rolloff*0.01, id/255), R8G8B8A8_UNORM -> GL_RGBA8
layout(binding = 3) uniform sampler2D t3;       // DS 1 depth (D24S8; GL depth texture, COMPARE_MODE NONE, .r = d)
uniform vec4 VPOSOffset;                        // cb2[0] = (1/W, 1/H, 1/ceil(W*sx), 1/ceil(H*sy)) (0x142246D35..0x142246E01)
uniform vec4 LightVector;                       // cb2[1]: sun = unit vector to the light, engine view; point = position (xyz), radius (w)
uniform vec4 LightColor;                        // cb2[2]: linear color (pow 2.2 on the CPU, DF 3.6)
layout(location = 0) out vec4 o0;               // SV_Target0 -> RT 0x21 (diffuse/3)
layout(location = 1) out vec4 o1;               // SV_Target1 -> RT 0x22 (specular)

// Lines 36..61 of 3321 and 3323; 1038..1063 of 3133 (+1002); 34..59 of 3107 (-2). Identical instruction streams.
// Out: r0.xy = D3D uv (= SV_Position * (1/W, 1/H)); r1.xyz = engine view-space position P; r2.z = z' (the remapped
// device depth that 3133 compares with SplitDistances.w). Other components as the asm leaves them.
void Fo4DFLightPosition(out vec4 r0, out vec4 r1, out vec4 r2)
{
    vec4 r3, r4, r5, r6;
    r0 = gl_FragCoord.xyxy * VPOSOffset;                                  // 36  mul r0.xyzw, v0.xyxy, cb2[0].xyzw
    r1.x = dFdxCoarse(r0.x);                                              // 37  deriv_rtx_coarse r1.x, r0.x
    r1.y = dFdyCoarse(r0.y);                                              // 38  deriv_rty_coarse r1.y, r0.y
    r1.x = textureGrad(t3, r0.xy, vec2(r1.x, r1.x), vec2(r1.y, r1.y)).x;  // 39  sample_d r1.x, r0.xyxx, t3.xyzw, s3, r1.xxxx, r1.yyyy
    bool m40 = FO4_L_0_01 >= r1.x;                                        // 40  ge r1.y, l(0.010000), r1.x
    if (m40)                                                              // 41  if_nz r1.y
    {
        r2.z = r1.x * 100.0;                                              // 42  mul r2.z, r1.x, l(100.000000)
        r3 = cb12_InvProj1P[0];                                           // 43  mov r3.xyzw, cb12[24].xyzw
        r4 = cb12_InvProj1P[1];                                           // 44  mov r4.xyzw, cb12[25].xyzw
        r5 = cb12_InvProj1P[2];                                           // 45  mov r5.xyzw, cb12[26].xyzw
        r6 = cb12_InvProj1P[3];                                           // 46  mov r6.xyzw, cb12[27].xyzw
    }
    else                                                                  // 47  else
    {
        r2.z = r1.x * FO4_L_1_01 + FO4_L_M0_01;                           // 48  mad r2.z, r1.x, l(1.010000), l(-0.010000)
        r3 = cb12_InvProj[0];                                             // 49  mov r3.xyzw, cb12[20].xyzw
        r4 = cb12_InvProj[1];                                             // 50  mov r4.xyzw, cb12[21].xyzw
        r5 = cb12_InvProj[2];                                             // 51  mov r5.xyzw, cb12[22].xyzw
        r6 = cb12_InvProj[3];                                             // 52  mov r6.xyzw, cb12[23].xyzw
    }                                                                     // 53  endif
    r0.zw = r0.zw * vec2(1.0, -1.0) + vec2(0.0, 1.0);                     // 54  mad r0.zw, r0.zzzw, l(0,0,1,-1), l(0,0,0,1)
    r2.xy = r0.zw * vec2(2.0, 2.0) + vec2(-1.0, -1.0);                    // 55  mad r2.xy, r0.zwzz, l(2,2,0,0), l(-1,-1,0,0)
    r2.w = 1.0;                                                           // 56  mov r2.w, l(1.000000)
    r1.x = dot(r3, r2);                                                   // 57  dp4 r1.x, r3.xyzw, r2.xyzw
    r1.y = dot(r4, r2);                                                   // 58  dp4 r1.y, r4.xyzw, r2.xyzw
    r1.z = dot(r5, r2);                                                   // 59  dp4 r1.z, r5.xyzw, r2.xyzw
    r0.z = dot(r6, r2);                                                   // 60  dp4 r0.z, r6.xyzw, r2.xyzw
    r1.xyz = vec3(d3d_div(r1.x, r0.z), d3d_div(r1.y, r0.z), d3d_div(r1.z, r0.z));   // 61  div r1.xyz, r1.xyzx, r0.zzzz
}
"

    Friend Const LightDirCore As String = "// 3321 lines 62..211 ('N'), with the 3133 line that computes the same value ('= M'). Inputs: r0, r1 as left by
// Fo4DFLightPosition. Outputs: o_r0 = r0 after line 211 (xyz = diffuse sum before /3, w = 1 - 0.5*rain) and
// o_r7 = r7.xyz (specular before the rain factor).
void Fo4DFLightDirCore(vec4 r0, vec4 r1, out vec4 o_r0, out vec3 o_r7)
{
    vec4 r2, r3, r4, r5, r6, r7, r8, r9;
    r2 = texture(t2, r0.xy);                          // 62 = 1064  sample r2.xyzw, r0.xyxx, t2.xyzw, s2
    r3 = texture(t0, r0.xy);                          // 63 = 1065  sample r3.xyzw, r0.xyxx, t0.xyzw, s0
    r0.xy = texture(t1, r0.xy).xy;                    // 64 = 1066  sample r0.xy, r0.xyxx, t1.xyzw, s1
    r0.xy = r0.xy * vec2(4.0, 4.0) + vec2(-2.0, -2.0);        // 65 = 1067  mad r0.xy, r0.xyxx, l(4,4,0,0), l(-2,-2,0,0)
    r0.z = dot(r0.xy, r0.xy);                         // 66 = 1068  dp2 r0.z, r0.xyxx, r0.xyxx
    r0.zw = -r0.zz * vec2(0.25, 0.5) + vec2(1.0, 1.0);        // 67 = 1069  mad r0.zw, -r0.zzzz, l(0,0,0.25,0.5), l(0,0,1,1)
    r0.z = d3d_sqrt(r0.z);                            // 68 = 1070  sqrt r0.z, r0.z
    r0.xy = r0.zz * r0.xy;                            // 69 = 1071  mul r0.xy, r0.zzzz, r0.xyxx
    r0.z = -r0.w;                                     // 70 = 1072  mov r0.z, -r0.w            (N = r0.xyz)
    r0.w = -r2.x + 1.0;                               // 71 = 1073  add r0.w, -r2.x, l(1.000000)  (1 - gloss)
    r1.w = dot(-r1.xyz, -r1.xyz);                     // 72 = 1074  dp3 r1.w, -r1.xyzx, -r1.xyzx
    r1.w = d3d_rsq(r1.w);                             // 73 = 1075  rsq r1.w, r1.w
    r4.xyz = r1.www * -r1.xyz;                        // 74 = 1076  mul r4.xyz, r1.wwww, -r1.xyzx   (V)
    r5.xyz = r3.www * r3.xyz;                         // 75 = 1199  mul r5.xyz, r3.wwww, r3.xyzx   (albedo * t0.a)
    r4.w = dot(r0.xyz, LightVector.xyz);              // 76 = 1200  dp3 r4.w, r0.xyzx, cb2[1].xyzx (NdotL)
    r5.w = d3d_max(r4.w, 0.0);                        // 77 = 1201  max r5.w, r4.w, l(0.000000)
    r6.x = d3d_min(r5.w, 1.0);                        // 78 = 1202  min r6.x, r5.w, l(1.000000)
    r6.y = d3d_sat(cb12_30.y);                        // 79 = 1203  mov_sat r6.y, cb12[30].y
    r6.y = -r6.y + 1.0;                               // 80 = 1204  add r6.y, -r6.y, l(1.000000)
    r6.z = r6.y * r6.y;                               // 81 = 1205  mul r6.z, r6.y, r6.y
    r6.z = r6.z * r6.z;                               // 82 = 1206  mul r6.z, r6.z, r6.z
    r6.y = -r6.y * r6.z + 1.0;                        // 83 = 1207  mad r6.y, -r6.y, r6.z, l(1.000000)   (rain)
    r2.w = r2.w * 255.0 + (-1.0);                     // 84 = 1208  mad r2.w, r2.w, l(255.000000), l(-1.000000)
    bool m85 = abs(r2.w) < 0.25;                      // 85 = 1209  lt r2.w, |r2.w|, l(0.250000)
    if (m85)                                          // 86 = 1210  if_nz r2.w            (id 1: hair, Kajiya-Kay)
    {
        r2.w = dot(r2.xyz, LightVector.xyz);          // 87 = 1211  dp3 r2.w, r2.xyzx, cb2[1].xyzx  (TdotL)
        r6.z = dot(r2.xyz, r4.xyz);                   // 88 = 1212  dp3 r6.z, r2.xyzx, r4.xyzx      (TdotV)
        r6.w = r2.w * r2.w;                           // 89 = 1213  mul r6.w, r2.w, r2.w
        r6.w = d3d_min(r6.w, 1.0);                    // 90 = 1214  min r6.w, r6.w, l(1.000000)
        r6.w = -r6.w + 1.0;                           // 91 = 1215  add r6.w, -r6.w, l(1.000000)
        r6.w = d3d_sqrt(r6.w);                        // 92 = 1219.x  sqrt r6.w, r6.w
        r7.x = r6.z * r6.z;                           // 93 = 1216  mul r7.x, r6.z, r6.z
        r7.x = d3d_min(r7.x, 1.0);                    // 94 = 1217  min r7.x, r7.x, l(1.000000)
        r7.x = -r7.x + 1.0;                           // 95 = 1218  add r7.x, -r7.x, l(1.000000)
        r8.x = sin(cb12_HairSpec[1].y);               // 96 = 1220  sincos r8.x, r9.x, cb12[29].y
        r9.x = cos(cb12_HairSpec[1].y);               // 96 = 1220
        r7.y = r6.w * r8.x;                           // 97 = 1221  mul r7.y, r6.w, r8.x
        r7.y = -r2.w * r9.x + -r7.y;                  // 98 = 1222  mad r7.y, -r2.w, r9.x, -r7.y
        r7.z = -r7.y * r7.y + 1.0;                    // 99 = 1223  mad r7.z, -r7.y, r7.y, l(1.000000)
        r7.xz = vec2(d3d_sqrt(r7.x), d3d_sqrt(r7.z)); // 100 = 1219.y, 1224  sqrt r7.xz, r7.xxzx
        r7.z = r7.x * r7.z;                           // 101 = 1225  mul r7.z, r7.x, r7.z
        r7.y = r7.y * r6.z + r7.z;                    // 102 = 1226  mad r7.y, r7.y, r6.z, r7.z
        r7.y = d3d_max(r7.y, 0.0);                    // 103 = 1227  max r7.y, r7.y, l(0.000000)
        r7.y = d3d_log2(r7.y);                        // 104 = 1228  log r7.y, r7.y
        r7.y = r7.y * cb12_HairSpec[0].w;             // 105 = 1229  mul r7.y, r7.y, cb12[28].w
        r7.y = d3d_exp2(r7.y);                        // 106 = 1230  exp r7.y, r7.y
        r7.y = d3d_sat(cb12_HairSpec[0].z * r7.y + r5.w);    // 107 = 1231  mad_sat r7.y, cb12[28].z, r7.y, r5.w
        r3.w = d3d_min(r3.w, r7.y);                   // 108 = 1232  min r3.w, r3.w, r7.y
        r8.x = sin(cb12_HairSpec[1].x);               // 109 = 1233  sincos r8.x, r9.x, cb12[29].x
        r9.x = cos(cb12_HairSpec[1].x);               // 109 = 1233
        r6.w = r6.w * r8.x;                           // 110 = 1234  mul r6.w, r6.w, r8.x
        r2.w = -r2.w * r9.x + -r6.w;                  // 111 = 1235  mad r2.w, -r2.w, r9.x, -r6.w
        r6.w = -r2.w * r2.w + 1.0;                    // 112 = 1236  mad r6.w, -r2.w, r2.w, l(1.000000)
        r6.w = d3d_sqrt(r6.w);                        // 113 = 1237  sqrt r6.w, r6.w
        r6.w = r7.x * r6.w;                           // 114 = 1238  mul r6.w, r7.x, r6.w
        r2.w = r2.w * r6.z + r6.w;                    // 115 = 1239  mad r2.w, r2.w, r6.z, r6.w
        r2.w = d3d_max(r2.w, 0.0);                    // 116 = 1240  max r2.w, r2.w, l(0.000000)
        r2.w = d3d_log2(r2.w);                        // 117 = 1241  log r2.w, r2.w
        r2.w = r2.w * cb12_HairSpec[0].y;             // 118 = 1242  mul r2.w, r2.w, cb12[28].y
        r2.w = d3d_exp2(r2.w);                        // 119 = 1243  exp r2.w, r2.w
        r2.w = r2.w * cb12_HairSpec[0].x;             // 120 = 1244  mul r2.w, r2.w, cb12[28].x
        r7.xyz = r2.www * LightColor.xyz;             // 121 = 1245  mul r7.xyz, r2.wwww, cb2[2].xyzx
        r7.xyz = r6.xxx * r7.xyz;                     // 122 = 1246  mul r7.xyz, r6.xxxx, r7.xyzx
        r2.w = 0.0;                                   // 123 = 1247  mov r2.w, l(0)   (wrap = 0)
    }
    else                                              // 124 = 1248  else
    {
        r2.w = r2.z * 100.0;                          // 125 = 1249  mul r2.w, r2.z, l(100.000000)   (wrap)
        r2.x = r2.x * 10.0 + 1.0;                     // 126 = 1250  mad r2.x, r2.x, l(10.000000), l(1.000000)
        r2.x = d3d_exp2(r2.x);                        // 127 = 1251  exp r2.x, r2.x
        r2.z = r6.y * FO4_L_M0_98 + 1.0;              // 128 = 1252  mad r2.z, r6.y, l(-0.980000), l(1.000000)
        r6.z = r2.z * r2.x;                           // 129 = 1253  mul r6.z, r2.z, r2.x
        r6.w = dot(r4.xyz, r0.xyz);                   // 130 = 1254  dp3 r6.w, r4.xyzx, r0.xyzx    (NdotV)
        r8.xyz = -r0.xyz * r6.www + r4.xyz;           // 131 = 1255  mad r8.xyz, -r0.xyzx, r6.wwww, r4.xyzx
        r9.xyz = -r0.xyz * r4.www + LightVector.xyz;  // 132 = 1256  mad r9.xyz, -r0.xyzx, r4.wwww, cb2[1].xyzx
        r7.w = dot(r8.xyz, r9.xyz);                   // 133 = 1257  dp3 r7.w, r8.xyzx, r9.xyzx
        r8.x = r0.w * r0.w;                           // 134 = 1258  mul r8.x, r0.w, r0.w
        r8.yz = r0.ww * r0.ww + vec2(FO4_L_0_57, FO4_L_0_09);    // 135 = 1259  mad r8.yz, r0.wwww, r0.wwww, l(0,0.57,0.09,0)
        r8.xy = vec2(d3d_div(r8.x, r8.y), d3d_div(r8.x, r8.z));  // 136 = 1260  div r8.xy, r8.xxxx, r8.yzyy
        r8.y = r8.y * FO4_L_0_45;                     // 137 = 1261  mul r8.y, r8.y, l(0.450000)
        r8.x = -r8.x * 0.5 + 1.0;                     // 138 = 1262  mad r8.x, -r8.x, l(0.500000), l(1.000000)
        r8.z = -r6.w * r6.w + 1.0;                    // 139 = 1263  mad r8.z, -r6.w, r6.w, l(1.000000)
        r8.w = -r4.w * r4.w + 1.0;                    // 140 = 1264  mad r8.w, -r4.w, r4.w, l(1.000000)
        r8.z = d3d_sat(r8.w * r8.z);                  // 141 = 1265  mul_sat r8.z, r8.w, r8.z
        r8.z = d3d_sqrt(r8.z);                        // 142 = 1266  sqrt r8.z, r8.z
        r8.w = d3d_max(r4.w, r6.w);                   // 143 = 1267  max r8.w, r4.w, r6.w
        r8.z = d3d_div(r8.z, r8.w);                   // 144 = 1268  div r8.z, r8.z, r8.w
        r7.w = d3d_max(r7.w, 0.0);                    // 145 = 1269  max r7.w, r7.w, l(0.000000)
        r7.w = r7.w * r8.y;                           // 146 = 1270  mul r7.w, r7.w, r8.y
        r7.w = r7.w * r8.z + r8.x;                    // 147 = 1271  mad r7.w, r7.w, r8.z, r8.x
        r3.w = r5.w * r7.w;                           // 148 = 1272  mul r3.w, r5.w, r7.w   (Oren-Nayar)
        r1.xyz = -r1.xyz * r1.www + LightVector.xyz;  // 149 = 1273  mad r1.xyz, -r1.xyzx, r1.wwww, cb2[1].xyzx
        r1.w = dot(r1.xyz, r1.xyz);                   // 150 = 1274  dp3 r1.w, r1.xyzx, r1.xyzx
        r1.w = d3d_rsq(r1.w);                         // 151 = 1275  rsq r1.w, r1.w
        r1.xyz = r1.www * r1.xyz;                     // 152 = 1276  mul r1.xyz, r1.wwww, r1.xyzx   (H)
        r6.w = d3d_sat(r6.w);                         // 153 = 1277  mov_sat r6.w, r6.w
        r1.w = d3d_sat(dot(r4.xyz, r1.xyz));          // 154 = 1278  dp3_sat r1.w, r4.xyzx, r1.xyzx  (VdotH)
        r1.x = d3d_sat(dot(r1.xyz, r0.xyz));          // 155 = 1279  dp3_sat r1.x, r1.xyzx, r0.xyzx  (NdotH)
        r1.y = r2.x * r2.z + 2.0;                     // 156 = 1280  mad r1.y, r2.x, r2.z, l(2.000000)
        r1.y = r1.y * FO4_L_INV_2PI;                  // 157 = 1281  mul r1.y, r1.y, l(0.159155)
        r1.z = d3d_log2(r1.x);                        // 158 = 1282  log r1.z, r1.x
        r1.z = r1.z * r6.z;                           // 159 = 1283  mul r1.z, r1.z, r6.z
        r1.z = d3d_exp2(r1.z);                        // 160 = 1284  exp r1.z, r1.z
        r1.y = r1.z * r1.y;                           // 161 = 1285  mul r1.y, r1.z, r1.y
        r1.z = d3d_max(r1.w, FO4_L_2POW_M23);         // 162 = 1286  max r1.z, r1.w, l(0.000000)  [token 0x34000000]
        r2.x = d3d_min(r6.x, r6.w);                   // 163 = 1287  min r2.x, r6.x, r6.w
        r1.x = r1.x + r1.x;                           // 164 = 1288  add r1.x, r1.x, r1.x
        r2.z = r1.x * r2.x;                           // 165 = 1289  mul r2.z, r1.x, r2.x
        bool m166 = r1.z >= r2.z;                     // 166 = 1290  ge r2.z, r1.z, r2.z
        bool m167 = r6.w == r2.x;                     // 167 = 1291  eq r2.x, r6.w, r2.x
        r5.w = d3d_div(r6.x, r6.w);                   // 168 = 1292  div r5.w, r6.x, r6.w
        r2.x = m167 ? 1.0 : r5.w;                     // 169 = 1293  movc r2.x, r2.x, l(1.000000), r5.w
        r1.x = r1.x * r2.x;                           // 170 = 1294  mul r1.x, r1.x, r2.x
        r1.x = d3d_div(r1.x, r1.z);                   // 171 = 1295  div r1.x, r1.x, r1.z
        r1.z = d3d_div(1.0, r6.w);                    // 172 = 1296  div r1.z, l(1,1,1,1), r6.w
        r1.x = m166 ? r1.x : r1.z;                    // 173 = 1297  movc r1.x, r2.z, r1.x, r1.z
        r1.z = -r1.w + 1.0;                           // 174 = 1298  add r1.z, -r1.w, l(1.000000)
        r1.w = r1.z * r1.z;                           // 175 = 1299  mul r1.w, r1.z, r1.z
        r1.w = r1.w * r1.w;                           // 176 = 1300  mul r1.w, r1.w, r1.w
        r2.x = r1.w * r1.z;                           // 177 = 1301  mul r2.x, r1.w, r1.z
        r1.z = -r1.z * r1.w + 1.0;                    // 178 = 1302  mad r1.z, -r1.z, r1.w, l(1.000000)
        r1.z = r1.z * FO4_L_0_2 + r2.x;               // 179 = 1303  mad r1.z, r1.z, l(0.200000), r2.x
        r1.z = d3d_min(r1.z, 1.0);                    // 180 = 1304  min r1.z, r1.z, l(1.000000)
        r1.x = r1.x * r1.z;                           // 181 = 1305  mul r1.x, r1.x, r1.z
        r1.x = r1.y * r1.x;                           // 182 = 1306  mul r1.x, r1.y, r1.x
        r1.x = r1.x * 0.25;                           // 183 = 1307  mul r1.x, r1.x, l(0.250000)
        r1.x = d3d_min(r1.x, 15.0);                   // 184 = 1308  min r1.x, r1.x, l(15.000000)
        r1.x = r2.y * r1.x;                           // 185 = 1309  mul r1.x, r2.y, r1.x   (* spec t2.y)
        r1.x = r1.x * FO4_L_PI;                       // 186 = 1310  mul r1.x, r1.x, l(3.141593)
        r1.xyz = r1.xxx * LightColor.xyz;             // 187 = 1311  mul r1.xyz, r1.xxxx, cb2[2].xyzx
        r7.xyz = r6.xxx * r1.xyz;                     // 188 = 1312  mul r7.xyz, r6.xxxx, r1.xyzx
    }                                                 // 189 = 1313  endif
    r0.x = d3d_sat(dot(r0.xyz, r4.xyz));              // 190 = 1314  dp3_sat r0.x, r0.xyzx, r4.xyzx
    r0.x = -r0.x + 1.0;                               // 191 = 1315  add r0.x, -r0.x, l(1.000000)
    r0.x = d3d_log2(r0.x);                            // 192 = 1316  log r0.x, r0.x
    r0.x = r0.x * FO4_L_0_01;                         // 193 = 1317  mul r0.x, r0.x, l(0.010000)
    r0.x = d3d_exp2(r0.x);                            // 194 = 1318  exp r0.x, r0.x
    r0.y = d3d_sat(dot(r4.xyz, -LightVector.xyz));    // 195 = 1319  dp3_sat r0.y, r4.xyzx, -cb2[1].xyzx
    r0.x = r0.y * r0.x;                               // 196 = 1320  mul r0.x, r0.y, r0.x
    r0.x = r6.x * r0.x;                               // 197 = 1321  mul r0.x, r6.x, r0.x
    r0.x = r0.w * r0.x;                               // 198 = 1322  mul r0.x, r0.w, r0.x     (rim)
    r0.xyz = r0.xxx * LightColor.xyz;                 // 199 = 1323  mul r0.xyz, r0.xxxx, cb2[2].xyzx
    r0.xyz = LightColor.xyz * r3.www + r0.xyz;        // 200 = 1324  mad r0.xyz, cb2[2].xyzx, r3.wwww, r0.xyzx
    r0.w = d3d_sat(-r4.w);                            // 201 = 1325  mov_sat r0.w, -r4.w
    r1.xyz = r5.xyz * r0.www;                         // 202 = 1326  mul r1.xyz, r5.xyzx, r0.wwww   (back-light)
    r0.xyz = LightColor.xyz * r1.xyz + r0.xyz;        // 203 = 1327  mad r0.xyz, cb2[2].xyzx, r1.xyzx, r0.xyzx
    r0.w = r2.w + r4.w;                               // 204 = 1328  add r0.w, r2.w, r4.w
    r1.x = r2.w + 1.0;                                // 205 = 1329  add r1.x, r2.w, l(1.000000)
    r0.w = d3d_sat(d3d_div(r0.w, r1.x));              // 206 = 1330  div_sat r0.w, r0.w, r1.x
    r0.w = -r6.x + r0.w;                              // 207 = 1331  add r0.w, -r6.x, r0.w
    r0.w = d3d_max(r0.w, 0.0);                        // 208 = 1332  max r0.w, r0.w, l(0.000000)
    r1.xyz = r0.www * LightColor.xyz;                 // 209 = 1333  mul r1.xyz, r0.wwww, cb2[2].xyzx
    r0.xyz = r1.xyz * r3.xyz + r0.xyz;                // 210 = 1334  mad r0.xyz, r1.xyzx, r3.xyzx, r0.xyzx   (wrap/sss)
    r0.w = r6.y * -0.5 + 1.0;                         // 211 = 1335  mad r0.w, r6.y, l(-0.500000), l(1.000000)
    o_r0 = r0;
    o_r7 = r7.xyz;
}
"

    Friend Const Body3321 As String = "// b10_DFLight_PS_rec3321_t00000201: directional + specular, no shadow (sun technique 0x201, DF 3.2).
void main()
{
    vec4 r0, r1, r2;
    Fo4DFLightPosition(r0, r1, r2);                   // 36..61
    vec4 c0; vec3 r7;
    Fo4DFLightDirCore(r0, r1, c0, r7);                // 62..211
    o1.xyz = c0.www * r7.xyz;                         // 212  mul o1.xyz, r0.wwww, r7.xyzx
    o0.xyz = c0.xyz * FO4_L_ONE_THIRD;                // 213  mul o0.xyz, r0.xyzx, l(0.333333, 0.333333, 0.333333, 0)
    o0.w = 0.0;                                       // 214  mov o0.w, l(0)
    o1.w = 1.0;                                       // 215  mov o1.w, l(1.000000)
}
"

    Friend Const Body3133 As String = "// b10_DFLight_PS_rec3133_t08200202: directional + specular + shadow (sun technique 0x08200202, DF 3.2, 12.1).
// The engine cascades (lines 1079..1188: FadeDistances cb2[10], ShadowMapProj cb2[11..19], ShadowSampleParam cb2[20],
// ShadowWorldScale cb2[21..23], t5 Texture2DArray + s5 comparison, 16 Poisson taps from the ICB) are REPLACED by the
// app's shadow factor, which takes the value r1.w holds after line 1188. The gate (1077) and the distance fade
// (1189..1195) are the engine's and stay; s multiplies every term exactly where the asm does (1336..1340).
layout(binding = 5) uniform sampler2D AppShadowFactor;   // APP input (not engine): .x = cascade result s in [0,1],
                                                         // D3D row order, W x H, NEAREST, sampled at the light uv
uniform vec4 SplitDistances;                    // cb2[9]  (const 7, byte 0x24): only .w read here (gate on z')
uniform vec4 ShadowFadeParam;                   // cb2[24] (const 12, byte 0x60): only .x read here (fade distance^2)
void main()
{
    vec4 r0, r1, r2;
    Fo4DFLightPosition(r0, r1, r2);                   // 1038..1063
    // r1.xyz = P (view), r2.z = z' (remapped device depth), r0.xy = uv
    bool m1077 = r2.z < SplitDistances.w;             // 1077  lt r2.y, r2.z, cb2[9].w
    if (m1077)                                        // 1078  if_nz r2.y
    {
        // 1079..1188 REPLACED (engine cascades). r1.w = value of the cascade selection of 1187..1188:
        r1.w = textureLod(AppShadowFactor, r0.xy, 0.0).x;
        r2.y = dot(r1.xyz, r1.xyz);                   // 1189  dp3 r2.y, r1.xyzx, r1.xyzx
        r2.y = d3d_sat(d3d_div(r2.y, ShadowFadeParam.x));   // 1190  div_sat r2.y, r2.y, cb2[24].x
        r2.y = r2.y * r2.y;                           // 1191  mul r2.y, r2.y, r2.y
        r2.y = r2.y * r2.y;                           // 1192  mul r2.y, r2.y, r2.y
        r2.y = -r2.y * r2.y + 1.0;                    // 1193  mad r2.y, -r2.y, r2.y, l(1.000000)
        r1.w = r1.w + (-1.0);                         // 1194  add r1.w, r1.w, l(-1.000000)
        r1.w = r2.y * r1.w + 1.0;                     // 1195  mad r1.w, r2.y, r1.w, l(1.000000)
    }
    else                                              // 1196  else
    {
        r1.w = 1.0;                                   // 1197  mov r1.w, l(1.000000)
    }                                                 // 1198  endif
    float s = r1.w;
    vec4 c0; vec3 r7;
    Fo4DFLightDirCore(r0, r1, c0, r7);                // 1064..1076, 1199..1335 (DFLIGHT_DIR_CORE; r1.w is not read there:
                                                      // the core's first read of r1.w follows its own write at 72 = 1074)
    vec3 t1336 = c0.www * r7.xyz;                     // 1336  mul r1.xyz, r0.wwww, r7.xyzx
    o1.xyz = vec3(s) * t1336;                         // 1337  mul o1.xyz, r1.wwww, r1.xyzx
    c0.xyz = vec3(s) * c0.xyz;                        // 1338  mul r0.xyz, r1.wwww, r0.xyzx
    c0.w = 0.0;                                       // 1339  mov r0.w, l(0)
    o0 = vec4(d3d_div(c0.x, 3.0), d3d_div(c0.y, 3.0), d3d_div(c0.z, 3.0), d3d_div(c0.w, 3.0));   // 1340  div o0.xyzw, r0.xyzw, l(3,3,3,3)
    o1.w = 1.0;                                       // 1341  mov o1.w, l(1.000000)
}
"

    Friend Const Body3323 As String = "// b10_DFLight_PS_rec3323_t00000204: point omni + specular (DF 3.4, ENV 14.2).
layout(binding = 5) uniform sampler2D AppShadowFactor;   // APP input: one channel per rig light (propuesta B)
uniform int uFillShadowChannel;                          // the rig light's channel (ShadowMapMath.LuzDelRig order)
uniform vec4 LightAttenuation;                  // cb2[3] (const 3, byte 0x0C): (x bias, y scale, z exponent) = NiLight+0x170..0x178
void main()
{
    vec4 r0, r1, r2, r3, r4, r5, r6, r7, r8;
    Fo4DFLightPosition(r0, r1, r2);                   // 36..61
    // App deviation (rig fill = directional light, propuesta D): the input of line 62 is the light DIRECTION in engine view;
    // with LightVector.w = 1 and LightAttenuation = (0, 0, 1, 0) lines 63..73 give att = 1 exactly.
    r2.xyz = LightVector.xyz;                         // 62  add r2.xyz, -r1.xyzx, cb2[1].xyzx (input substituted)
    r0.z = dot(r2.xyz, r2.xyz);                       // 63  dp3 r0.z, r2.xyzx, r2.xyzx
    r0.w = d3d_sqrt(r0.z);                            // 64  sqrt r0.w, r0.z
    r0.w = d3d_sat(d3d_div(r0.w, LightVector.w));     // 65  div_sat r0.w, r0.w, cb2[1].w
    r0.w = d3d_log2(r0.w);                            // 66  log r0.w, r0.w
    r0.w = r0.w * LightAttenuation.z;                 // 67  mul r0.w, r0.w, cb2[3].z
    r0.w = d3d_exp2(r0.w);                            // 68  exp r0.w, r0.w
    r0.w = d3d_sat(LightAttenuation.y * r0.w + LightAttenuation.x);   // 69  mad_sat r0.w, cb2[3].y, r0.w, cb2[3].x
    r0.w = -r0.w + 1.0;                               // 70  add r0.w, -r0.w, l(1.000000)
    r0.w = d3d_log2(r0.w);                            // 71  log r0.w, r0.w
    r0.w = r0.w * FO4_L_2_2;                          // 72  mul r0.w, r0.w, l(2.200000)
    r0.w = d3d_exp2(r0.w);                            // 73  exp r0.w, r0.w    (att)
    bool m74 = FO4_L_0_001 >= r0.w;                   // 74  ge r1.w, l(0.001000), r0.w
    if (m74)                                          // 75  if_nz r1.w
    {
        o0 = vec4(0.0);                               // 76  mov o0.xyzw, l(0,0,0,0)
        o1 = vec4(0.0);                               // 77  mov o1.xyzw, l(0,0,0,0)
        return;                                       // 78  ret
    }                                                 // 79  endif
    r0.z = d3d_rsq(r0.z);                             // 80  rsq r0.z, r0.z
    r2.xyz = r0.zzz * r2.xyz;                         // 81  mul r2.xyz, r0.zzzz, r2.xyzx     (L)
    // 82..83 and 100 are implicit-LOD `sample` in non-uniform flow (after the early ret / inside a branch):
    // textureLod(.., 0) -- FILT 0 point with a single-level texture returns the same texel for any LOD (notas D4).
    r3 = textureLod(t2, r0.xy, 0.0);                  // 82  sample r3.xyzw, r0.xyxx, t2.xyzw, s2
    r4.xy = textureLod(t1, r0.xy, 0.0).xy;            // 83  sample r4.xy, r0.xyxx, t1.xyzw, s1
    r4.xy = r4.xy * vec2(4.0, 4.0) + vec2(-2.0, -2.0);        // 84  mad r4.xy, r4.xyxx, l(4,4,0,0), l(-2,-2,0,0)
    r0.z = dot(r4.xy, r4.xy);                         // 85  dp2 r0.z, r4.xyxx, r4.xyxx
    r4.zw = -r0.zz * vec2(0.25, 0.5) + vec2(1.0, 1.0);        // 86  mad r4.zw, -r0.zzzz, l(0,0,0.25,0.5), l(0,0,1,1)
    r0.z = d3d_sqrt(r4.z);                            // 87  sqrt r0.z, r4.z
    r4.xy = r0.zz * r4.xy;                            // 88  mul r4.xy, r0.zzzz, r4.xyxx
    r4.z = -r4.w;                                     // 89  mov r4.z, -r4.w        (N = r4.xyz)
    r0.z = -r3.x + 1.0;                               // 90  add r0.z, -r3.x, l(1.000000)   (1 - gloss)
    r1.w = dot(-r1.xyz, -r1.xyz);                     // 91  dp3 r1.w, -r1.xyzx, -r1.xyzx
    r1.w = d3d_rsq(r1.w);                             // 92  rsq r1.w, r1.w
    r5.xyz = r1.www * -r1.xyz;                        // 93  mul r5.xyz, r1.wwww, -r1.xyzx   (V)
    r2.w = dot(r4.xyz, r2.xyz);                       // 94  dp3 r2.w, r4.xyzx, r2.xyzx      (NdotL)
    r4.w = d3d_max(r2.w, 0.0);                        // 95  max r4.w, r2.w, l(0.000000)
    r5.w = d3d_min(r4.w, 1.0);                        // 96  min r5.w, r4.w, l(1.000000)
    r3.w = r3.w * 255.0 + (-1.0);                     // 97  mad r3.w, r3.w, l(255.000000), l(-1.000000)
    bool m98 = abs(r3.w) < 0.25;                      // 98  lt r3.w, |r3.w|, l(0.250000)
    if (m98)                                          // 99  if_nz r3.w       (id 1: hair)
    {
        r0.x = textureLod(t0, r0.xy, 0.0).w;          // 100 sample r0.x, r0.xyxx, t0.wxyz, s0   (t0.a)
        r0.y = dot(r3.xyz, r2.xyz);                   // 101 dp3 r0.y, r3.xyzx, r2.xyzx    (TdotL)
        r3.z = dot(r3.xyz, r5.xyz);                   // 102 dp3 r3.z, r3.xyzx, r5.xyzx    (TdotV)
        r3.w = r0.y * r0.y;                           // 103 mul r3.w, r0.y, r0.y
        r3.w = d3d_min(r3.w, 1.0);                    // 104 min r3.w, r3.w, l(1.000000)
        r3.w = -r3.w + 1.0;                           // 105 add r3.w, -r3.w, l(1.000000)
        r3.w = d3d_sqrt(r3.w);                        // 106 sqrt r3.w, r3.w
        r6.x = r3.z * r3.z;                           // 107 mul r6.x, r3.z, r3.z
        r6.x = d3d_min(r6.x, 1.0);                    // 108 min r6.x, r6.x, l(1.000000)
        r6.x = -r6.x + 1.0;                           // 109 add r6.x, -r6.x, l(1.000000)
        r7.x = sin(cb12_HairSpec[1].y);               // 110 sincos r7.x, r8.x, cb12[29].y
        r8.x = cos(cb12_HairSpec[1].y);               // 110
        r6.y = r3.w * r7.x;                           // 111 mul r6.y, r3.w, r7.x
        r6.y = -r0.y * r8.x + -r6.y;                  // 112 mad r6.y, -r0.y, r8.x, -r6.y
        r6.z = -r6.y * r6.y + 1.0;                    // 113 mad r6.z, -r6.y, r6.y, l(1.000000)
        r6.xz = vec2(d3d_sqrt(r6.x), d3d_sqrt(r6.z)); // 114 sqrt r6.xz, r6.xxzx
        r6.z = r6.x * r6.z;                           // 115 mul r6.z, r6.x, r6.z
        r6.y = r6.y * r3.z + r6.z;                    // 116 mad r6.y, r6.y, r3.z, r6.z
        r6.y = d3d_max(r6.y, 0.0);                    // 117 max r6.y, r6.y, l(0.000000)
        r6.y = d3d_log2(r6.y);                        // 118 log r6.y, r6.y
        r6.y = r6.y * cb12_HairSpec[0].w;             // 119 mul r6.y, r6.y, cb12[28].w
        r6.y = d3d_exp2(r6.y);                        // 120 exp r6.y, r6.y
        r6.y = d3d_sat(cb12_HairSpec[0].z * r6.y + r4.w);   // 121 mad_sat r6.y, cb12[28].z, r6.y, r4.w
        r0.x = d3d_min(r0.x, r6.y);                   // 122 min r0.x, r0.x, r6.y
        r7.x = sin(cb12_HairSpec[1].x);               // 123 sincos r7.x, r8.x, cb12[29].x
        r8.x = cos(cb12_HairSpec[1].x);               // 123
        r3.w = r3.w * r7.x;                           // 124 mul r3.w, r3.w, r7.x
        r0.y = -r0.y * r8.x + -r3.w;                  // 125 mad r0.y, -r0.y, r8.x, -r3.w
        r3.w = -r0.y * r0.y + 1.0;                    // 126 mad r3.w, -r0.y, r0.y, l(1.000000)
        r3.w = d3d_sqrt(r3.w);                        // 127 sqrt r3.w, r3.w
        r3.w = r6.x * r3.w;                           // 128 mul r3.w, r6.x, r3.w
        r0.y = r0.y * r3.z + r3.w;                    // 129 mad r0.y, r0.y, r3.z, r3.w
        r0.y = d3d_max(r0.y, 0.0);                    // 130 max r0.y, r0.y, l(0.000000)
        r0.y = d3d_log2(r0.y);                        // 131 log r0.y, r0.y
        r0.y = r0.y * cb12_HairSpec[0].y;             // 132 mul r0.y, r0.y, cb12[28].y
        r0.y = d3d_exp2(r0.y);                        // 133 exp r0.y, r0.y
        r0.y = r0.y * cb12_HairSpec[0].x;             // 134 mul r0.y, r0.y, cb12[28].x
        r6.xyz = r0.yyy * LightColor.xyz;             // 135 mul r6.xyz, r0.yyyy, cb2[2].xyzx
        r6.xyz = r5.www * r6.xyz;                     // 136 mul r6.xyz, r5.wwww, r6.xyzx
    }
    else                                              // 137 else
    {
        r0.y = r3.x * 10.0 + 1.0;                     // 138 mad r0.y, r3.x, l(10.000000), l(1.000000)
        r0.y = d3d_exp2(r0.y);                        // 139 exp r0.y, r0.y
        r3.x = dot(r5.xyz, r4.xyz);                   // 140 dp3 r3.x, r5.xyzx, r4.xyzx   (NdotV)
        r7.xyz = -r4.xyz * r3.xxx + r5.xyz;           // 141 mad r7.xyz, -r4.xyzx, r3.xxxx, r5.xyzx
        r8.xyz = -r4.xyz * r2.www + r2.xyz;           // 142 mad r8.xyz, -r4.xyzx, r2.wwww, r2.xyzx
        r3.z = dot(r7.xyz, r8.xyz);                   // 143 dp3 r3.z, r7.xyzx, r8.xyzx
        r3.w = r0.z * r0.z;                           // 144 mul r3.w, r0.z, r0.z
        r7.xy = r0.zz * r0.zz + vec2(FO4_L_0_57, FO4_L_0_09);    // 145 mad r7.xy, r0.zzzz, r0.zzzz, l(0.57,0.09,0,0)
        r7.xy = vec2(d3d_div(r3.w, r7.x), d3d_div(r3.w, r7.y));  // 146 div r7.xy, r3.wwww, r7.xyxx
        r3.w = r7.y * FO4_L_0_45;                     // 147 mul r3.w, r7.y, l(0.450000)
        r6.w = -r7.x * 0.5 + 1.0;                     // 148 mad r6.w, -r7.x, l(0.500000), l(1.000000)
        r7.x = -r3.x * r3.x + 1.0;                    // 149 mad r7.x, -r3.x, r3.x, l(1.000000)
        r7.y = -r2.w * r2.w + 1.0;                    // 150 mad r7.y, -r2.w, r2.w, l(1.000000)
        r7.x = d3d_sat(r7.y * r7.x);                  // 151 mul_sat r7.x, r7.y, r7.x
        r7.x = d3d_sqrt(r7.x);                        // 152 sqrt r7.x, r7.x
        r2.w = d3d_max(r2.w, r3.x);                   // 153 max r2.w, r2.w, r3.x
        r2.w = d3d_div(r7.x, r2.w);                   // 154 div r2.w, r7.x, r2.w
        r3.z = d3d_max(r3.z, 0.0);                    // 155 max r3.z, r3.z, l(0.000000)
        r3.z = r3.z * r3.w;                           // 156 mul r3.z, r3.z, r3.w
        r2.w = r3.z * r2.w + r6.w;                    // 157 mad r2.w, r3.z, r2.w, r6.w
        r0.x = r2.w * r4.w;                           // 158 mul r0.x, r2.w, r4.w         (Oren-Nayar)
        r1.xyz = -r1.xyz * r1.www + r2.xyz;           // 159 mad r1.xyz, -r1.xyzx, r1.wwww, r2.xyzx
        r1.w = dot(r1.xyz, r1.xyz);                   // 160 dp3 r1.w, r1.xyzx, r1.xyzx
        r1.w = d3d_rsq(r1.w);                         // 161 rsq r1.w, r1.w
        r1.xyz = r1.www * r1.xyz;                     // 162 mul r1.xyz, r1.wwww, r1.xyzx   (H)
        r3.x = d3d_sat(r3.x);                         // 163 mov_sat r3.x, r3.x
        r1.w = d3d_sat(dot(r5.xyz, r1.xyz));          // 164 dp3_sat r1.w, r5.xyzx, r1.xyzx  (VdotH)
        r1.x = d3d_sat(dot(r1.xyz, r4.xyz));          // 165 dp3_sat r1.x, r1.xyzx, r4.xyzx  (NdotH)
        r1.y = r0.y + 2.0;                            // 166 add r1.y, r0.y, l(2.000000)
        r1.y = r1.y * FO4_L_INV_2PI;                  // 167 mul r1.y, r1.y, l(0.159155)
        r1.z = d3d_log2(r1.x);                        // 168 log r1.z, r1.x
        r0.y = r0.y * r1.z;                           // 169 mul r0.y, r0.y, r1.z
        r0.y = d3d_exp2(r0.y);                        // 170 exp r0.y, r0.y
        r0.y = r0.y * r1.y;                           // 171 mul r0.y, r0.y, r1.y
        r1.y = d3d_max(r1.w, FO4_L_2POW_M23);         // 172 max r1.y, r1.w, l(0.000000)  [token 0x34000000]
        r1.z = d3d_min(r5.w, r3.x);                   // 173 min r1.z, r5.w, r3.x
        r1.x = r1.x + r1.x;                           // 174 add r1.x, r1.x, r1.x
        r2.w = r1.x * r1.z;                           // 175 mul r2.w, r1.x, r1.z
        bool m176 = r1.y >= r2.w;                     // 176 ge r2.w, r1.y, r2.w
        bool m177 = r3.x == r1.z;                     // 177 eq r1.z, r3.x, r1.z
        r3.z = d3d_div(r5.w, r3.x);                   // 178 div r3.z, r5.w, r3.x
        r1.z = m177 ? 1.0 : r3.z;                     // 179 movc r1.z, r1.z, l(1.000000), r3.z
        r1.x = r1.x * r1.z;                           // 180 mul r1.x, r1.x, r1.z
        r1.x = d3d_div(r1.x, r1.y);                   // 181 div r1.x, r1.x, r1.y
        r1.y = d3d_div(1.0, r3.x);                    // 182 div r1.y, l(1,1,1,1), r3.x
        r1.x = m176 ? r1.x : r1.y;                    // 183 movc r1.x, r2.w, r1.x, r1.y
        r1.y = -r1.w + 1.0;                           // 184 add r1.y, -r1.w, l(1.000000)
        r1.z = r1.y * r1.y;                           // 185 mul r1.z, r1.y, r1.y
        r1.z = r1.z * r1.z;                           // 186 mul r1.z, r1.z, r1.z
        r1.w = r1.z * r1.y;                           // 187 mul r1.w, r1.z, r1.y
        r1.y = -r1.y * r1.z + 1.0;                    // 188 mad r1.y, -r1.y, r1.z, l(1.000000)
        r1.y = r1.y * FO4_L_0_2 + r1.w;               // 189 mad r1.y, r1.y, l(0.200000), r1.w
        r1.y = d3d_min(r1.y, 1.0);                    // 190 min r1.y, r1.y, l(1.000000)
        r1.x = r1.x * r1.y;                           // 191 mul r1.x, r1.x, r1.y
        r0.y = r0.y * r1.x;                           // 192 mul r0.y, r0.y, r1.x
        r0.y = r0.y * 0.25;                           // 193 mul r0.y, r0.y, l(0.250000)
        r0.y = d3d_min(r0.y, 15.0);                   // 194 min r0.y, r0.y, l(15.000000)
        r0.y = r3.y * r0.y;                           // 195 mul r0.y, r3.y, r0.y   (* spec t2.y)
        r0.y = r0.y * FO4_L_PI;                       // 196 mul r0.y, r0.y, l(3.141593)
        r1.xyz = r0.yyy * LightColor.xyz;             // 197 mul r1.xyz, r0.yyyy, cb2[2].xyzx
        r6.xyz = r5.www * r1.xyz;                     // 198 mul r6.xyz, r5.wwww, r1.xyzx
    }                                                 // 199 endif
    r0.y = d3d_sat(dot(r4.xyz, r5.xyz));              // 200 dp3_sat r0.y, r4.xyzx, r5.xyzx
    r0.y = -r0.y + 1.0;                               // 201 add r0.y, -r0.y, l(1.000000)
    r0.y = d3d_log2(r0.y);                            // 202 log r0.y, r0.y
    r0.y = r0.y * FO4_L_0_01;                         // 203 mul r0.y, r0.y, l(0.010000)
    r0.y = d3d_exp2(r0.y);                            // 204 exp r0.y, r0.y
    r1.x = d3d_sat(dot(r5.xyz, -r2.xyz));             // 205 dp3_sat r1.x, r5.xyzx, -r2.xyzx
    r0.y = r0.y * r1.x;                               // 206 mul r0.y, r0.y, r1.x
    r0.y = r5.w * r0.y;                               // 207 mul r0.y, r5.w, r0.y
    r0.y = r0.z * r0.y;                               // 208 mul r0.y, r0.z, r0.y      (rim)
    r1.xyz = r0.yyy * LightColor.xyz;                 // 209 mul r1.xyz, r0.yyyy, cb2[2].xyzx
    r0.xyz = LightColor.xyz * r0.xxx + r1.xyz;        // 210 mad r0.xyz, cb2[2].xyzx, r0.xxxx, r1.xyzx
    o1.xyz = r0.www * r6.xyz;                         // 211 mul o1.xyz, r0.wwww, r6.xyzx
    r0.xyz = r0.www * r0.xyz;                         // 212 mul r0.xyz, r0.wwww, r0.xyzx
    r0.w = 0.0;                                       // 213 mov r0.w, l(0)
    o0 = vec4(d3d_div(r0.x, 3.0), d3d_div(r0.y, 3.0), d3d_div(r0.z, 3.0), d3d_div(r0.w, 3.0));   // 214 div o0.xyzw, r0.xyzw, l(3,3,3,3)
    o1.w = 1.0;                                       // 215 mov o1.w, l(1.000000)
    // App deviation (rig fills cast shadows, user decision rev-21 b): the fill's shadow factor multiplies all its terms.
    // The light uv of line 36 (r0 holds the colour by now): the shadow RT is in the same D3D row order as this pass.
    float sFill = textureLod(AppShadowFactor, gl_FragCoord.xy * VPOSOffset.xy, 0.0)[uFillShadowChannel];
    o0.xyz *= sFill; o1.xyz *= sFill;
}
"

    Friend Const Body3107 As String = "// b10_DFLight_PS_rec3107_t00020000: AMBIENT (DirectionalAmbient), full-screen like the sun (DF 3.3, ENV 15.4).
// Position lines 34..59 = DFLIGHT_COMMON (3321 numbering - 2). t0 is not read by this PS.
uniform vec4 DirectionalAmbient[3];             // cb2[6..8] (const 6, byte 0x18): amb_c(N) = pow(dot(cb2[6+c], (N_view,1)), 2.2)
void main()
{
    vec4 r0, r1, r2, r3, r4;
    Fo4DFLightPosition(r0, r1, r2);                   // 34..59
    r2.xyz = texture(t2, r0.xy).xyw;                  // 60  sample r2.xyz, r0.xyxx, t2.xywz, s2  -> (x, y, w)
    r0.xy = texture(t1, r0.xy).xy;                    // 61  sample r0.xy, r0.xyxx, t1.xyzw, s1
    r0.xy = r0.xy * vec2(4.0, 4.0) + vec2(-2.0, -2.0);        // 62  mad r0.xy, r0.xyxx, l(4,4,0,0), l(-2,-2,0,0)
    r0.z = dot(r0.xy, r0.xy);                         // 63  dp2 r0.z, r0.xyxx, r0.xyxx
    r0.zw = -r0.zz * vec2(0.25, 0.5) + vec2(1.0, 1.0);        // 64  mad r0.zw, -r0.zzzz, l(0,0,0.25,0.5), l(0,0,1,1)
    r0.z = d3d_sqrt(r0.z);                            // 65  sqrt r0.z, r0.z
    r3.xy = r0.zz * r0.xy;                            // 66  mul r3.xy, r0.zzzz, r0.xyxx
    r3.z = -r0.w;                                     // 67  mov r3.z, -r0.w          (N = r3.xyz)
    r0.x = dot(-r1.xyz, -r1.xyz);                     // 68  dp3 r0.x, -r1.xyzx, -r1.xyzx
    r0.x = d3d_rsq(r0.x);                             // 69  rsq r0.x, r0.x
    r0.xyz = r0.xxx * -r1.xyz;                        // 70  mul r0.xyz, r0.xxxx, -r1.xyzx   (V)
    r3.w = 1.0;                                       // 71  mov r3.w, l(1.000000)
    r0.w = dot(DirectionalAmbient[0], r3);            // 72  dp4 r0.w, cb2[6].xyzw, r3.xyzw
    r1.x = dot(DirectionalAmbient[1], r3);            // 73  dp4 r1.x, cb2[7].xyzw, r3.xyzw
    r1.y = dot(DirectionalAmbient[2], r3);            // 74  dp4 r1.y, cb2[8].xyzw, r3.xyzw
    r4.x = d3d_log2(r0.w);                            // 75  log r4.x, r0.w
    r4.y = d3d_log2(r1.x);                            // 76  log r4.y, r1.x
    r4.z = d3d_log2(r1.y);                            // 77  log r4.z, r1.y
    r1.xyz = r4.xyz * vec3(FO4_L_2_2);                // 78  mul r1.xyz, r4.xyzx, l(2.2, 2.2, 2.2, 0)
    r1.xyz = vec3(d3d_exp2(r1.x), d3d_exp2(r1.y), d3d_exp2(r1.z));   // 79  exp r1.xyz, r1.xyzx
    r0.w = dot(r3.xyz, r0.xyz);                       // 80  dp3 r0.w, r3.xyzx, r0.xyzx    (NdotV)
    r1.w = r0.w + r0.w;                               // 81  add r1.w, r0.w, r0.w
    r3.xyz = r1.www * r3.xyz + -r0.xyz;               // 82  mad r3.xyz, r1.wwww, r3.xyzx, -r0.xyzx   (R)
    r0.w = d3d_sat(r0.w);                             // 83  mov_sat r0.w, r0.w
    r0.x = -r0.w + 1.0;                               // 84  add r0.x, -r0.w, l(1.000000)
    r0.y = -r2.x + 3.0;                               // 85  add r0.y, -r2.x, l(3.000000)
    r0.x = d3d_log2(r0.x);                            // 86  log r0.x, r0.x
    r0.x = r0.x * r0.y;                               // 87  mul r0.x, r0.x, r0.y
    r0.x = d3d_exp2(r0.x);                            // 88  exp r0.x, r0.x
    r0.x = r0.x * 0.25;                               // 89  mul r0.x, r0.x, l(0.250000)
    r3.w = 1.0;                                       // 90  mov r3.w, l(1.000000)
    r0.y = dot(DirectionalAmbient[0], r3);            // 91  dp4 r0.y, cb2[6].xyzw, r3.xyzw
    r0.z = dot(DirectionalAmbient[1], r3);            // 92  dp4 r0.z, cb2[7].xyzw, r3.xyzw
    r0.w = dot(DirectionalAmbient[2], r3);            // 93  dp4 r0.w, cb2[8].xyzw, r3.xyzw
    r3.x = d3d_log2(r0.y);                            // 94  log r3.x, r0.y
    r3.y = d3d_log2(r0.z);                            // 95  log r3.y, r0.z
    r3.z = d3d_log2(r0.w);                            // 96  log r3.z, r0.w
    r0.yzw = r3.xyz * vec3(FO4_L_2_2);                // 97  mul r0.yzw, r3.xxyz, l(0, 2.2, 2.2, 2.2)
    r0.yzw = vec3(d3d_exp2(r0.y), d3d_exp2(r0.z), d3d_exp2(r0.w));   // 98  exp r0.yzw, r0.yyzw
    r0.xyz = r0.xxx * r0.yzw;                         // 99  mul r0.xyz, r0.xxxx, r0.yzwy
    r0.w = r2.z * 255.0 + (-1.0);                     // 100 mad r0.w, r2.z, l(255.000000), l(-1.000000)
    bool m101 = abs(r0.w) < 0.25;                     // 101 lt r0.w, |r0.w|, l(0.250000)
    r0.w = m101 ? 0.0 : r2.y;                         // 102 movc r0.w, r0.w, l(0), r2.y
    o1.xyz = r0.www * r0.xyz;                         // 103 mul o1.xyz, r0.wwww, r0.xyzx
    o1.w = 1.0;                                       // 104 mov o1.w, l(1.000000)
    o0.xyz = r1.xyz * FO4_L_ONE_THIRD;                // 105 mul o0.xyz, r1.xyzx, l(0.333333, 0.333333, 0.333333, 0)
    o0.w = 0.0;                                       // 106 mov o0.w, l(0)
}
"

    Friend Const Body3432 As String = "// b11_DFComposite_PS_rec3432_t00000088: composite pass 1 -> RT 2 (DF 4.3, 17.1): o = 3*albedo*t5 + (id != 5 ? t4+t6 : 0).
// Samplers (SetupTechnique 0x142216AC0, DF 4.2): s0..s7 CLAMP + POINT -> CLAMP_TO_EDGE, NEAREST, single level.
layout(binding = 0) uniform sampler2D t0;       // RT 0x1A albedo (GL_SRGB8_ALPHA8)
layout(binding = 3) uniform sampler2D t3;       // RT 0x1E (GL_RGBA8): .w = id/255
layout(binding = 4) uniform sampler2D t4;       // RT 0x1F emissive (GL_SRGB8_ALPHA8; RGBEMIT = 1, DF 10)
layout(binding = 5) uniform sampler2D t5;       // RT 0x21 diffuse light/3 (GL_R11F_G11F_B10F)
layout(binding = 6) uniform sampler2D t6;       // RT 0x22 specular light (GL_R11F_G11F_B10F; RGBSPEC = 1, DF 10)
uniform vec4 VPOSOffset;                        // cb2[0] = (1/W, 1/H, 1/sx, 1/sy) (0x142217560..0x1422175D0); .xy read
layout(location = 0) out vec4 o0;               // -> RT 2 (GL_R11F_G11F_B10F)
void main()
{
    vec4 r0, r1, r2, r3;
    r0.xy = gl_FragCoord.xy * VPOSOffset.xy;          // 34  mul r0.xy, v0.xyxx, cb2[0].xyxx
    r1 = textureLod(t0, r0.xy, 0.0);                  // 35  sample_l r1.xyzw, r0.xyxx, t0.xyzw, s0, l(0)
    r0.z = textureLod(t3, r0.xy, 0.0).w;              // 36  sample_l r0.z, r0.xyxx, t3.xywz, s3, l(0)   (t3.w)
    r2.xyz = textureLod(t5, r0.xy, 0.0).xyz;          // 37  sample_l r2.xyz, r0.xyxx, t5.xyzw, s5, l(0)
    r2.xyz = r1.xyz * r2.xyz;                         // 38  mul r2.xyz, r1.xyzx, r2.xyzx
    r1.xyz = r2.xyz * vec3(3.0);                      // 39  mul r1.xyz, r2.xyzx, l(3,3,3,0)
    r0.z = r0.z * 255.0 + (-5.0);                     // 40  mad r0.z, r0.z, l(255.000000), l(-5.000000)
    bool m41 = abs(r0.z) >= 0.25;                     // 41  ge r0.z, |r0.z|, l(0.250000)
    if (m41)                                          // 42  if_nz r0.z          (not skin)
    {
        r3.xyz = textureLod(t4, r0.xy, 0.0).xyz;      // 43  sample r3.xyz, r0.xyxx, t4.xyzw, s4  (implicit LOD in a branch -> notas D4)
        r0.xyz = textureLod(t6, r0.xy, 0.0).xyz;      // 44  sample_l r0.xyz, r0.xyxx, t6.xyzw, s6, l(0)
        r0.xyz = r3.xyz + r0.xyz;                     // 45  add r0.xyz, r3.xyzx, r0.xyzx
        r1.xyz = r2.xyz * vec3(3.0) + r0.xyz;         // 46  mad r1.xyz, r2.xyzx, l(3,3,3,0), r0.xyzx
    }                                                 // 47  endif
    o0 = r1;                                          // 48  mov o0.xyzw, r1.xyzw
}
"

    Friend Const Body3495 As String = "// b11_DFComposite_PS_rec3495_t00000B60: composite pass 2 -> RT 1 (DF 4.3, 17; ENV 3.2).
// SKIPPED by scope, each replaced by the value the preview has: t14 (SSR, RT 7) sample = (0,0,0,0) => R = env
// (DF 17.5); t9 (AO) sample = 1; fog block 311..360 => amount 0 => o = C (line 361). cb12[30].y (rain) = 0 is an
// uploaded value, the code stays. Samplers (DF 4.2, 17.3, ENV 3.1): s1..s7, s10 CLAMP + POINT; s15 CLAMP + POINT;
// s8 CLAMP + ANISOTROPIC (MinLOD 0, MaxLOD FLT_MAX) -> GL CLAMP_TO_EDGE, LINEAR_MIPMAP_LINEAR / LINEAR,
// TEXTURE_MAX_ANISOTROPY 16 (sample_l: explicit LOD), GL_TEXTURE_CUBE_MAP_SEAMLESS enabled.
layout(binding = 1)  uniform sampler2D t1;              // RT 0x1B normal (GL_RG16)
layout(binding = 2)  uniform sampler2D t2;              // RT 0x1D (SSR mask, (cube+1)/255, sqrt(0.02 E), w) (GL_RGBA8)
layout(binding = 3)  uniform sampler2D t3;              // RT 0x1E (gloss, spec, rolloff, id/255) (GL_RGBA8)
layout(binding = 4)  uniform sampler2D t4;              // RT 0x1F emissive (GL_SRGB8_ALPHA8)
layout(binding = 5)  uniform sampler2D t5;              // RT 0x21 (GL_R11F_G11F_B10F)
layout(binding = 6)  uniform sampler2D t6;              // RT 0x22 (GL_R11F_G11F_B10F)
layout(binding = 7)  uniform sampler2D t7;              // DS 1 depth (.r = d)
layout(binding = 8)  uniform samplerCubeArray t8;       // EnvMapArray, B8G8R8A8_UNORM_SRGB -> GL_SRGB8_ALPHA8 (ENV 13.3)
layout(binding = 10) uniform sampler2D t10;             // RT 2 = composite pass 1 output (GL_R11F_G11F_B10F)
layout(binding = 15) uniform sampler2D t15;             // RT 0x28 linear view z, mip 0 (GL_R32F) (DF 17.3)
uniform vec4 VPOSOffset;                        // cb2[0] = (1/W, 1/H, 1/sx, 1/sy) (0x142217560..0x1422175D0)
uniform vec4 SSSSSParams;                       // cb0[0] = (fSSSSSPower 4.0, fSSSSSDepthCorrection 2.5, fSSSSS1stPersonDepthMultiplier 9.0, -)
uniform vec4 SSLRParams0;                       // cb0[1]: only .x read (fSSLRIntensity 1.0)
uniform vec4 SSLRParams1;                       // cb0[2]: only .z read (fSSLRBlendingPower 1.0)
layout(location = 0) out vec4 o0;               // -> RT 1 (GL_R11F_G11F_B10F)
layout(location = 1) out vec4 coverageOut;      // APP: the post's coverage of an engine-geometry pixel (rev-19)
uniform float uViewportH;                       // APP: the target height (A.5)

// One SSS tap = the repeated instruction block 120..134 (and 137..151, 154..168, 170..184, 187..201, 203..217,
// 220..234, 236..250, 253..267, 270..282; the last one has no else because its result register r3 already holds the
// centre). Line numbers below are those of the first instance. uvi = tap uv; r3c = centre colour (t10 at the centre);
// r0z = k (1 + fp*cb0[0].z); r0w = zc (k * t15 centre).
vec3 Fo4SssTap(vec2 uvi, vec3 r3c, float r0z, float r0w)
{
    float r3w = textureLod(t3, uvi, 0.0).w;           // 120 sample_l r3.w, r7.xyxx, t3.xyzw, s3, l(0)
    r3w = r3w * 255.0 + (-5.0);                       // 121 mad r3.w, r3.w, l(255.000000), l(-5.000000)
    bool m122 = abs(r3w) < 0.25;                      // 122 lt r3.w, |r3.w|, l(0.250000)
    if (m122)                                         // 123 if_nz r3.w
    {
        vec3 r8 = textureLod(t10, uvi, 0.0).xyz;      // 124 sample_l r8.xyz, r7.xyxx, t10.xyzw, s10, l(0)
        float s = textureLod(t15, uvi, 0.0).x;        // 125 sample_l r3.w, r7.xyxx, t15.yzwx, s15, l(0)   (t15.x)
        float r5x = SSSSSParams.y * FO4_L_0_1;        // 126 mul r5.x, cb0[0].y, l(0.100000)
        s = -s * r0z + r0w;                           // 127 mad r3.w, -r3.w, r0.z, r0.w
        s = abs(s) * r5x;                             // 128 mul r3.w, |r3.w|, r5.x
        s = d3d_min(s, 1.0);                          // 129 min r3.w, r3.w, l(1.000000)
        vec3 r9 = r3c + -r8;                          // 130 add r9.xyz, r3.xyzx, -r8.xyzx
        return vec3(s) * r9 + r8;                     // 131 mad r8.xyz, r3.wwww, r9.xyzx, r8.xyzx
    }
    return r3c;                                       // 132..134 else: mov r8.xyz, r3.xyzx
}

void main()
{
    vec4 r0, r1, r2, r3, r4, r5, r6, r7, r8, r9;
    // App deviation (A.5): pass 2 runs LOWER_LEFT into the GL-order scene target; SV_Position of the D3D row order is
    // (x, H - y_gl), exact at pixel centres. Every read below is a D3D uv on a D3D-order texture.
    r0.xy = vec2(gl_FragCoord.x, uViewportH - gl_FragCoord.y) * VPOSOffset.xy;   // 50  mul r0.xy, v0.xyxx, cb2[0].xyxx
    coverageOut = vec4(1.0);   // APP (rev-19): every pixel this PS runs on passed GREATER at z = 1: it is engine geometry
    r1.xyz = textureLod(t3, r0.xy, 0.0).xyw;          // 51  sample_l r1.xyz, r0.xyxx, t3.xywz, s3, l(0) -> (gloss, spec, id)
    r0.z = textureLod(t7, r0.xy, 0.0).x;              // 52  sample_l r0.z, r0.xyxx, t7.yzxw, s7, l(0)   (depth)
    bool m53 = FO4_L_0_01 >= r0.z;                    // 53  ge r0.w, l(0.010000), r0.z   (first-person range)
    if (m53)                                          // 54  if_nz r0.w
    {
        r2.z = r0.z * 100.0;                          // 55  mul r2.z, r0.z, l(100.000000)
        r3 = cb12_InvProj1P[0];                       // 56  mov r3.xyzw, cb12[24].xyzw
        r4 = cb12_InvProj1P[1];                       // 57  mov r4.xyzw, cb12[25].xyzw
        r5 = cb12_InvProj1P[2];                       // 58  mov r5.xyzw, cb12[26].xyzw
        r6 = cb12_InvProj1P[3];                       // 59  mov r6.xyzw, cb12[27].xyzw
    }
    else                                              // 60  else
    {
        r2.z = r0.z * FO4_L_1_01 + FO4_L_M0_01;       // 61  mad r2.z, r0.z, l(1.010000), l(-0.010000)
        r3 = cb12_InvProj[0];                         // 62  mov r3.xyzw, cb12[20].xyzw
        r4 = cb12_InvProj[1];                         // 63  mov r4.xyzw, cb12[21].xyzw
        r5 = cb12_InvProj[2];                         // 64  mov r5.xyzw, cb12[22].xyzw
        r6 = cb12_InvProj[3];                         // 65  mov r6.xyzw, cb12[23].xyzw
    }                                                 // 66  endif
    r7.x = r0.x * VPOSOffset.z;                       // 67  mul r7.x, r0.x, cb2[0].z
    r7.z = -r0.y * VPOSOffset.w + 1.0;                // 68  mad r7.z, -r0.y, cb2[0].w, l(1.000000)
    r2.xy = r7.xz * vec2(2.0, 2.0) + vec2(-1.0, -1.0);        // 69  mad r2.xy, r7.xzxx, l(2,2,0,0), l(-1,-1,0,0)
    r2.w = 1.0;                                       // 70  mov r2.w, l(1.000000)
    r3.x = dot(r3, r2);                               // 71  dp4 r3.x, r3.xyzw, r2.xyzw
    r3.y = dot(r4, r2);                               // 72  dp4 r3.y, r4.xyzw, r2.xyzw
    r3.z = dot(r5, r2);                               // 73  dp4 r3.z, r5.xyzw, r2.xyzw
    r0.z = dot(r6, r2);                               // 74  dp4 r0.z, r6.xyzw, r2.xyzw
    r2.xyz = vec3(d3d_div(r3.x, r0.z), d3d_div(r3.y, r0.z), d3d_div(r3.z, r0.z));   // 75  div r2.xyz, r3.xyzx, r0.zzzz  (P)
    r3.xyz = textureLod(t10, r0.xy, 0.0).xyz;         // 76  sample_l r3.xyz, r0.xyxx, t10.xyzw, s10, l(0)
    r4.xy = textureLod(t2, r0.xy, 0.0).yz;            // 77  sample_l r4.xy, r0.xyxx, t2.yzxw, s2, l(0) -> (t2.y, t2.z)
    bool m78 = FO4_L_0_001961 < r4.x;                 // 78  lt r0.z, l(0.001961), r4.x
    if (m78)                                          // 79  if_nz r0.z          (envmap, ENV 3.2)
    {
        r4.zw = textureLod(t1, r0.xy, 0.0).xy;        // 80  sample_l r4.zw, r0.xyxx, t1.zwxy, s1, l(0) -> (t1.x, t1.y)
        r4.zw = r4.zw * vec2(4.0, 4.0) + vec2(-2.0, -2.0);    // 81  mad r4.zw, r4.zzzw, l(0,0,4,4), l(0,0,-2,-2)
        r0.z = dot(r4.zw, r4.zw);                     // 82  dp2 r0.z, r4.zwzz, r4.zwzz
        r5.xy = -r0.zz * vec2(0.25, 0.5) + vec2(1.0, 1.0);    // 83  mad r5.xy, -r0.zzzz, l(0.25,0.5,0,0), l(1,1,0,0)
        r0.z = d3d_sqrt(r5.x);                        // 84  sqrt r0.z, r5.x
        r6.xy = r0.zz * r4.zw;                        // 85  mul r6.xy, r0.zzzz, r4.zwzz
        r6.z = -r5.y;                                 // 86  mov r6.z, -r5.y          (N)
        r0.z = dot(-r2.xyz, -r2.xyz);                 // 87  dp3 r0.z, -r2.xyzx, -r2.xyzx
        r0.z = d3d_rsq(r0.z);                         // 88  rsq r0.z, r0.z
        r5.xyz = r0.zzz * -r2.xyz;                    // 89  mul r5.xyz, r0.zzzz, -r2.xyzx    (V)
        r0.z = dot(r5.xyz, r6.xyz);                   // 90  dp3 r0.z, r5.xyzx, r6.xyzx
        r0.z = r0.z + r0.z;                           // 91  add r0.z, r0.z, r0.z
        r5.xyz = r6.xyz * -r0.zzz + r5.xyz;           // 92  mad r5.xyz, r6.xyzx, -r0.zzzz, r5.xyzx   (Rv)
        r6.x = dot(cb12_ViewToWorld[0].xyz, r5.xyz);  // 93  dp3 r6.x, cb12[12].xyzx, r5.xyzx
        r6.y = dot(cb12_ViewToWorld[1].xyz, r5.xyz);  // 94  dp3 r6.y, cb12[13].xyzx, r5.xyzx
        r6.z = dot(cb12_ViewToWorld[2].xyz, r5.xyz);  // 95  dp3 r6.z, cb12[14].xyzx, r5.xyzx    (R, world axes)
        r0.z = -r1.x + 1.0;                           // 96  add r0.z, -r1.x, l(1.000000)
        r0.z = r0.z * 6.0;                            // 97  mul r0.z, r0.z, l(6.000000)
        r0.z = r2.z * FO4_L_1_512 + r0.z;             // 98  mad r0.z, r2.z, l(0.001953), r0.z      (lod)
        r1.w = r4.x * 255.0 + (-1.0);                 // 99  mad r1.w, r4.x, l(255.000000), l(-1.000000)
        r6.w = floor(r1.w);                           // 100 round_ni r6.w, r1.w                   (array slice)
        r4.xzw = textureLod(t8, r6, r0.z).xyz;        // 101 sample_l r4.xzw, r6.xyzw, t8.xwyz, s8, r0.z -> (x, y, z)
        r0.z = dot(r4.xzw, vec3(FO4_L_LUMA_R, FO4_L_LUMA_G, FO4_L_LUMA_B));   // 102 dp3 r0.z, r4.xzwx, l(0.299,0.587,0.114,0)
        r1.w = cb12_30.y * FO4_L_0_9;                 // 103 mul r1.w, cb12[30].y, l(0.900000)
        r5.xyz = -r4.xzw + r0.zzz;                    // 104 add r5.xyz, -r4.xzwx, r0.zzzz
        r4.xzw = r1.www * r5.xyz + r4.xzw;            // 105 mad r4.xzw, r1.wwww, r5.xxyz, r4.xxzw
    }
    else                                              // 106 else
    {
        r4.xzw = vec3(0.0);                           // 107 mov r4.xzw, l(0,0,0,0)
    }                                                 // 108 endif
    r5.xyz = r1.zzz * vec3(255.0) + vec3(-5.0, -2.0, -3.0);  // 109 mad r5.xyz, r1.zzzz, l(255,255,255,0), l(-5,-2,-3,0)
    bool m110x = abs(r5.x) < 0.25;                    // 110 lt r5.xyz, |r5.xyzx|, l(0.25,0.25,0.25,0)   (id 5)
    bool m110y = abs(r5.y) < 0.25;                    // 110                                             (id 2)
    bool m110z = abs(r5.z) < 0.25;                    // 110                                             (id 3)
    if (m110x)                                        // 111 if_nz r5.x          (skin: SSS, DF 17.1)
    {
        r6.xyz = textureLod(t4, r0.xy, 0.0).xyz;      // 112 sample r6.xyz, r0.xyxx, t4.xyzw, s4  (implicit LOD in a branch -> notas D4)
        r0.z = m53 ? 1.0 : 0.0;                       // 113 and r0.z, r0.w, l(0x3f800000)
        r0.z = r0.z * SSSSSParams.z + 1.0;            // 114 mad r0.z, r0.z, cb0[0].z, l(1.000000)     (k)
        r0.w = textureLod(t15, r0.xy, 0.0).x;         // 115 sample_l r0.w, r0.xyxx, t15.yzwx, s15, l(0)
        r0.w = r0.z * r0.w;                           // 116 mul r0.w, r0.z, r0.w                       (zc)
        r1.zw = SSSSSParams.xx * vec2(0.078125, FO4_L_0_13889);   // 117 mul r1.zw, cb0[0].xxxx, l(0,0,0.078125,0.138890)
        r1.zw = vec2(d3d_div(r1.z, r0.w), d3d_div(r1.w, r0.w));   // 118 div r1.zw, r1.zzzw, r0.wwww       (step)
        r7 = r1.zwzw * vec4(-2.0, -2.0, FO4_L_M1_28, FO4_L_M1_28) + r0.xyxy;   // 119 mad r7.xyzw, r1.zwzw, l(-2,-2,-1.28,-1.28), r0.xyxy
        r8.xyz = Fo4SssTap(r7.xy, r3.xyz, r0.z, r0.w);            // 120..134 (tap -2)
        r8.xyz = r8.xyz * FO4_W_SSS_M2;                           // 135 mul r8.xyz, r8.xyzx, l(0.004717, 0.000185, 0.000051, 0)
        r8.xyz = r3.xyz * FO4_W_SSS_0 + r8.xyz;                   // 136 mad r8.xyz, r3.xyzx, l(0.560479, 0.669086, 0.784728, 0), r8.xyzx
        r7.xyz = Fo4SssTap(r7.zw, r3.xyz, r0.z, r0.w);            // 137..151 (tap -1.28)
        r7.xyz = r7.xyz * FO4_W_SSS_128 + r8.xyz;                 // 152 mad r7.xyz, r7.xyzx, l(0.019283, 0.002820, 0.000842, 0), r8.xyzx
        r8 = r1.zwzw * vec4(FO4_L_M0_72, FO4_L_M0_72, FO4_L_M0_32, FO4_L_M0_32) + r0.xyxy;   // 153 mad r8.xyzw, r1.zwzw, l(-0.72,-0.72,-0.32,-0.32), r0.xyxy
        r9.xyz = Fo4SssTap(r8.xy, r3.xyz, r0.z, r0.w);            // 154..168 (tap -0.72)
        r7.xyz = r9.xyz * FO4_W_SSS_072 + r7.xyz;                 // 169 mad r7.xyz, r9.xyzx, l(0.036390, 0.013100, 0.006437, 0), r7.xyzx
        r8.xyz = Fo4SssTap(r8.zw, r3.xyz, r0.z, r0.w);            // 170..184 (tap -0.32)
        r7.xyz = r8.xyz * FO4_W_SSS_032 + r7.xyz;                 // 185 mad r7.xyz, r8.xyzx, l(0.082190, 0.035861, 0.020926, 0), r7.xyzx
        r8 = r1.zwzw * vec4(FO4_L_M0_08, FO4_L_M0_08, FO4_L_0_08, FO4_L_0_08) + r0.xyxy;     // 186 mad r8.xyzw, r1.zwzw, l(-0.08,-0.08,0.08,0.08), r0.xyxy
        r9.xyz = Fo4SssTap(r8.xy, r3.xyz, r0.z, r0.w);            // 187..201 (tap -0.08)
        r7.xyz = r9.xyz * FO4_W_SSS_008 + r7.xyz;                 // 202 mad r7.xyz, r9.xyzx, l(0.077180, 0.113491, 0.079380, 0), r7.xyzx
        r8.xyz = Fo4SssTap(r8.zw, r3.xyz, r0.z, r0.w);            // 203..217 (tap +0.08)
        r7.xyz = r8.xyz * FO4_W_SSS_008 + r7.xyz;                 // 218 mad r7.xyz, r8.xyzx, l(0.077180, 0.113491, 0.079380, 0), r7.xyzx
        r8 = r1.zwzw * vec4(FO4_L_0_32, FO4_L_0_32, FO4_L_0_72, FO4_L_0_72) + r0.xyxy;       // 219 mad r8.xyzw, r1.zwzw, l(0.32,0.32,0.72,0.72), r0.xyxy
        r9.xyz = Fo4SssTap(r8.xy, r3.xyz, r0.z, r0.w);            // 220..234 (tap +0.32)
        r7.xyz = r9.xyz * FO4_W_SSS_032 + r7.xyz;                 // 235 mad r7.xyz, r9.xyzx, l(0.082190, 0.035861, 0.020926, 0), r7.xyzx
        r8.xyz = Fo4SssTap(r8.zw, r3.xyz, r0.z, r0.w);            // 236..250 (tap +0.72)
        r7.xyz = r8.xyz * FO4_W_SSS_072 + r7.xyz;                 // 251 mad r7.xyz, r8.xyzx, l(0.036390, 0.013100, 0.006437, 0), r7.xyzx
        r5.xw = r1.zw * vec2(FO4_L_1_28, FO4_L_1_28) + r0.xy;     // 252 mad r5.xw, r1.zzzw, l(1.28,0,0,1.28), r0.xxxy
        r8.xyz = Fo4SssTap(r5.xw, r3.xyz, r0.z, r0.w);            // 253..267 (tap +1.28)
        r7.xyz = r8.xyz * FO4_W_SSS_128 + r7.xyz;                 // 268 mad r7.xyz, r8.xyzx, l(0.019283, 0.002820, 0.000842, 0), r7.xyzx
        r1.zw = r1.zw * vec2(2.0, 2.0) + r0.xy;                   // 269 mad r1.zw, r1.zzzw, l(0,0,2,2), r0.xxxy
        r3.xyz = Fo4SssTap(r1.zw, r3.xyz, r0.z, r0.w);            // 270..282 (tap +2; asm also clobbers r0.z, r1.w: dead after)
        r7.xyz = r3.xyz * FO4_W_SSS_P2 + r7.xyz;                  // 283 mad r7.xyz, r3.xyzx, l(0.004717, 0.000185, 0.000051, 0), r7.xyzx
        r8.xyz = textureLod(t6, r0.xy, 0.0).xyz;                  // 284 sample_l r8.xyz, r0.xyxx, t6.xyzw, s6, l(0)
        r6.xyz = r6.xyz + r8.xyz;                                 // 285 add r6.xyz, r6.xyzx, r8.xyzx
        r3.xyz = r6.xyz + r7.xyz;                                 // 286 add r3.xyz, r6.xyzx, r7.xyzx
    }                                                 // 287 endif
    bool m288 = m110z || m110y;                       // 288 or r0.z, r5.z, r5.y
    if (!m288)                                        // 289 if_z r0.z           (id 2 / 3 -> 0)
    {
        r5.xyz = textureLod(t5, r0.xy, 0.0).xyz;      // 290 sample_l r5.xyz, r0.xyxx, t5.xyzw, s5, l(0)
        r5.xyz = r5.xyz * vec3(3.0);                  // 291 mul r5.xyz, r5.xyzx, l(3,3,3,0)
        r0.z = r1.y * 3.0;                            // 292 mul r0.z, r1.y, l(3.000000)
        r0.w = d3d_sat(r1.x + FO4_L_M0_3);            // 293 add_sat r0.w, r1.x, l(-0.300000)
        r0.w = d3d_rsq(r0.w);                         // 294 rsq r0.w, r0.w
        r0.w = d3d_div(1.0, r0.w);                    // 295 div r0.w, l(1,1,1,1), r0.w
        r0.w = d3d_min(r0.w, 1.0);                    // 296 min r0.w, r0.w, l(1.000000)
        r0.z = r0.w * r0.z;                           // 297 mul r0.z, r0.w, r0.z
        r0.w = r4.y * r4.y;                           // 298 mul r0.w, r4.y, r4.y
        r0.w = r0.w * 50.0;                           // 299 mul r0.w, r0.w, l(50.000000)
        // 300 min r0.xy, r0.xyxx, cb2[5].xyxx: feeds only the substituted samples 301 and 309 -> not emitted.
        r1 = vec4(0.0);                               // 301 sample r1.xyzw, r0.xyxx, t14.xyzw, s14 -> SUBSTITUTED (0,0,0,0): no SSR (DF 17.5)
        r1.w = r1.w * SSLRParams1.z;                  // 302 mul r1.w, r1.w, cb0[2].z
        r1.w = d3d_min(r1.w, 1.0);                    // 303 min r1.w, r1.w, l(1.000000)
        r1.xyz = r1.xyz * SSLRParams0.xxx + -r4.xzw;  // 304 mad r1.xyz, r1.xyzx, cb0[1].xxxx, -r4.xzwx
        r1.xyz = r1.www * r1.xyz + r4.xzw;            // 305 mad r1.xyz, r1.wwww, r1.xyzx, r4.xzwx    (R = env)
        r1.xyz = r0.zzz * r1.xyz;                     // 306 mul r1.xyz, r0.zzzz, r1.xyzx
        r1.xyz = r0.www * r1.xyz;                     // 307 mul r1.xyz, r0.wwww, r1.xyzx
        r1.xyz = r1.xyz * r5.xyz + r3.xyz;            // 308 mad r1.xyz, r1.xyzx, r5.xyzx, r3.xyzx   (C)
        r0.x = 1.0;                                   // 309 sample r0.x, r0.xyxx, t9.xyzw, s9 -> SUBSTITUTED 1: AO not bound (scope)
        r0.yzw = r0.xxx * r1.xyz;                     // 310 mul r0.yzw, r0.xxxx, r1.xxyz
        // 311..360 fog SKIPPED (scope): amount r1.w (343..344) = 0.
        o0.xyz = r0.yzw;                              // 361 mad o0.xyz, r1.wwww, r1.xyzx, r0.yzwy  with r1.w = 0
        o0.w = 1.0;                                   // 362 mov o0.w, l(1.000000)
    }
    else                                              // 363 else
    {
        o0 = vec4(0.0);                               // 364 mov o0.xyzw, l(0,0,0,0)
    }                                                 // 365 endif
}
"

    Friend Const Vertex_Light As String = Header430 & Prelude & D3d11SemanticsSource.Glsl & Vs_Light
    Friend Const Vertex_Composite As String = Header430 & Prelude & D3d11SemanticsSource.Glsl & Vs_Composite
    Friend Const Fragment_3321 As String = Header430Deriv & Prelude & D3d11SemanticsSource.Glsl & Cb12 & LightCommon & LightDirCore & Body3321
    Friend Const Fragment_3133 As String = Header430Deriv & Prelude & D3d11SemanticsSource.Glsl & Cb12 & LightCommon & LightDirCore & Body3133
    Friend Const Fragment_3323 As String = Header430Deriv & Prelude & D3d11SemanticsSource.Glsl & Cb12 & LightCommon & Body3323
    Friend Const Fragment_3107 As String = Header430Deriv & Prelude & D3d11SemanticsSource.Glsl & Cb12 & LightCommon & Body3107
    Friend Const Fragment_3432 As String = Header430 & Prelude & D3d11SemanticsSource.Glsl & Body3432
    Friend Const Fragment_3495 As String = Header430 & Prelude & D3d11SemanticsSource.Glsl & Cb12 & Body3495

    ''' <summary>Every GLSL text of this module, for the glsl-ascii gate (FaceTintCompositor.AllShaderSources).</summary>
    Friend Function AllSources() As (Name As String, Text As String)()
        Return {("FO4-DF-HEADER430", Header430), ("FO4-DF-HEADER430DERIV", Header430Deriv), ("FO4-DF-PRELUDE", Prelude), ("FO4-DF-VS_LIGHT", Vs_Light), ("FO4-DF-VS_COMPOSITE", Vs_Composite), ("FO4-DF-CB12", Cb12), ("FO4-DF-LIGHTCOMMON", LightCommon), ("FO4-DF-LIGHTDIRCORE", LightDirCore), ("FO4-DF-BODY3321", Body3321), ("FO4-DF-BODY3133", Body3133), ("FO4-DF-BODY3323", Body3323), ("FO4-DF-BODY3107", Body3107), ("FO4-DF-BODY3432", Body3432), ("FO4-DF-BODY3495", Body3495), ("FO4-DF-VERTEX_LIGHT", Vertex_Light), ("FO4-DF-VERTEX_COMPOSITE", Vertex_Composite), ("FO4-DF-FRAGMENT_3321", Fragment_3321), ("FO4-DF-FRAGMENT_3133", Fragment_3133), ("FO4-DF-FRAGMENT_3323", Fragment_3323), ("FO4-DF-FRAGMENT_3107", Fragment_3107), ("FO4-DF-FRAGMENT_3432", Fragment_3432), ("FO4-DF-FRAGMENT_3495", Fragment_3495)}
    End Function
End Module
