Imports NiflySharp
Imports NiflySharp.Blocks
Imports NiflySharp.Structs
Imports SysHalf = System.Half
Imports SysNumerics = System.Numerics

''' <summary>
''' IShapeGeometry adapter for the BSTriShape family (BSTriShape, BSSubIndexTriShape,
''' BSDynamicTriShape, BSSegmentedTriShape, BSMeshLODTriShape).  Vertex/triangle data lives
''' inline in the BSTriShape block (BSVertexData for FO4, BSVertexDataSSE for SSE), and the
''' skin partition is regenerated by NiflySharp's UpdateSkinPartitions on save — this adapter
''' does NOT touch the partition itself.
'''
''' Tangent / Bitangent semantics (the "INVERTIDAS swap"):
''' BSTriShape stores what the NIF format calls "Tangent" (ByteVector3 sbyte) and
''' "Bitangent" (BitangentX float/half + BitangentY/Z sbyte).  Empirically (Wardrobe_Manager
''' renderer + FO4 shaders) the correct interpretation is:
'''     renderer Tangent   = NIF Bitangent   (BitangentX/Y/Z)
'''     renderer Bitangent = NIF Tangent     (Tangent ByteVector3)
''' This adapter encapsulates that swap.  GetTangents/GetBitangents return the renderer-side
''' values; SetTangents/SetBitangents accept renderer-side values and route them back to the
''' opposite NIF field.  Callers never see the swap.
'''
''' Half-precision detail: when the BSTriShape is FO4 half-precision the renderer-side bitangent
''' (NIF Tangent) must be read directly from BSVertexData.Tangent rather than through
''' tri.Tangents — the NiflySharp Vector3 getter has a known decode mismatch for that path.
''' SSE and FO4 full-precision use tri.Tangents normally.
''' </summary>
Public Class BSTriShapeGeometry
    Implements IShapeGeometry

    Private ReadOnly _tri As BSTriShape
    Private ReadOnly _nif As Nifcontent_Class_Manolo

    Public Sub New(tri As BSTriShape, nif As Nifcontent_Class_Manolo)
        If tri Is Nothing Then Throw New ArgumentNullException(NameOf(tri))
        If nif Is Nothing Then Throw New ArgumentNullException(NameOf(nif))
        _tri = tri
        _nif = nif
    End Sub

    ' ─────────────── Identity ───────────────
    Public ReadOnly Property BackingShape As INiShape Implements IShapeGeometry.BackingShape
        Get
            Return _tri
        End Get
    End Property

    Public ReadOnly Property Name As String Implements IShapeGeometry.Name
        Get
            Return If(_tri?.Name?.String, "")
        End Get
    End Property

    Public ReadOnly Property Version As NiVersion Implements IShapeGeometry.Version
        Get
            Return _nif.Header.Version
        End Get
    End Property

    ' ─────────────── Counts and presence ───────────────
    Public ReadOnly Property VertexCount As Integer Implements IShapeGeometry.VertexCount
        Get
            Return _tri.VertexCount
        End Get
    End Property

    Public ReadOnly Property TriangleCount As Integer Implements IShapeGeometry.TriangleCount
        Get
            Return _tri.TriangleCount
        End Get
    End Property

    Public ReadOnly Property HasNormals As Boolean Implements IShapeGeometry.HasNormals
        Get
            Return _tri.HasNormals
        End Get
    End Property

    Public ReadOnly Property HasTangents As Boolean Implements IShapeGeometry.HasTangents
        Get
            Return _tri.HasTangents
        End Get
    End Property

    Public ReadOnly Property HasUVs As Boolean Implements IShapeGeometry.HasUVs
        Get
            Return _tri.HasUVs
        End Get
    End Property

    Public ReadOnly Property HasVertexColors As Boolean Implements IShapeGeometry.HasVertexColors
        Get
            Return _tri.HasVertexColors
        End Get
    End Property

    Public ReadOnly Property HasEyeData As Boolean Implements IShapeGeometry.HasEyeData
        Get
            Return _tri.HasEyeData
        End Get
    End Property

    Public ReadOnly Property IsSkinned As Boolean Implements IShapeGeometry.IsSkinned
        Get
            Return _tri.IsSkinned
        End Get
    End Property

    Public ReadOnly Property Bounds As BoundingSphere Implements IShapeGeometry.Bounds
        Get
            Return _tri.Bounds
        End Get
    End Property

    ' ─────────────── Read ───────────────
    Public Function GetVertexPositions() As List(Of SysNumerics.Vector3) Implements IShapeGeometry.GetVertexPositions
        Return If(_tri.VertexPositions?.ToList(), New List(Of SysNumerics.Vector3)())
    End Function

    Public Function GetNormals() As List(Of SysNumerics.Vector3) Implements IShapeGeometry.GetNormals
        If Not _tri.HasNormals Then Return New List(Of SysNumerics.Vector3)()
        Return If(_tri.Normals?.ToList(), New List(Of SysNumerics.Vector3)())
    End Function

    ''' <summary>
    ''' Renderer-convention tangent.  Sourced from NIF "Bitangent" fields (BitangentX/Y/Z)
    ''' due to the INVERTIDAS swap.  Routes by precision: SSE uses BSVertexDataSSE.BitangentX
    ''' (float) + BitangentY/Z (sbyte).  FO4 full-precision uses BSVertexData.BitangentX (float).
    ''' FO4 half-precision uses BSVertexData.BitangentXHalf (Half).  In every case
    ''' BitangentY/Z are sbyte values that decode as ((b And &HFF) / 255 * 2 - 1).
    ''' </summary>
    Public Function GetTangents() As List(Of SysNumerics.Vector3) Implements IShapeGeometry.GetTangents
        If Not _tri.HasTangents Then Return New List(Of SysNumerics.Vector3)()
        Dim n As Integer = _tri.VertexCount
        Dim result As New List(Of SysNumerics.Vector3)(n)

        If Version.IsSSE Then
            Dim vd = _tri.VertexDataSSE
            If vd Is Nothing OrElse vd.Count <> n Then
                ' Defensive: SSE shape with no vertex data — caller would have bigger problems but don't crash here.
                For i = 0 To n - 1 : result.Add(SysNumerics.Vector3.Zero) : Next
                Return result
            End If
            For i = 0 To n - 1
                result.Add(DecodeBitangent(CSng(vd(i).BitangentX), vd(i).BitangentY, vd(i).BitangentZ))
            Next
        Else
            Dim vd = _tri.VertexData
            If vd Is Nothing OrElse vd.Count <> n Then
                For i = 0 To n - 1 : result.Add(SysNumerics.Vector3.Zero) : Next
                Return result
            End If
            If _tri.IsFullPrecision Then
                For i = 0 To n - 1
                    result.Add(DecodeBitangent(vd(i).BitangentX, vd(i).BitangentY, vd(i).BitangentZ))
                Next
            Else
                For i = 0 To n - 1
                    result.Add(DecodeBitangent(CSng(vd(i).BitangentXHalf), vd(i).BitangentY, vd(i).BitangentZ))
                Next
            End If
        End If
        Return result
    End Function

    ''' <summary>
    ''' Renderer-convention bitangent.  Sourced from NIF "Tangent" field (BSVertexData.Tangent
    ''' ByteVector3) due to the INVERTIDAS swap.  For SSE and FO4 full-precision we route
    ''' through tri.Tangents (NiflySharp decodes ByteVector3 → Vector3 correctly there).  For
    ''' FO4 half-precision we read BSVertexData.Tangent directly with the byte normalization,
    ''' to bypass a known NiflySharp Vector3 getter mismatch on that path.
    ''' </summary>
    Public Function GetBitangents() As List(Of SysNumerics.Vector3) Implements IShapeGeometry.GetBitangents
        If Not _tri.HasTangents Then Return New List(Of SysNumerics.Vector3)()
        Dim n As Integer = _tri.VertexCount
        Dim result As New List(Of SysNumerics.Vector3)(n)

        If Version.IsSSE OrElse _tri.IsFullPrecision Then
            Dim src = _tri.Tangents
            If src Is Nothing OrElse src.Count <> n Then
                For i = 0 To n - 1 : result.Add(SysNumerics.Vector3.Zero) : Next
                Return result
            End If
            For i = 0 To n - 1
                Dim v = src(i)
                result.Add(NormalizeOrZero(v))
            Next
        Else
            ' FO4 half-precision: read BSVertexData.Tangent (ByteVector3 with sbyte fields) directly.
            Dim vd = _tri.VertexData
            If vd Is Nothing OrElse vd.Count <> n Then
                For i = 0 To n - 1 : result.Add(SysNumerics.Vector3.Zero) : Next
                Return result
            End If
            For i = 0 To n - 1
                Dim t = vd(i).Tangent
                result.Add(NormalizeOrZero(DecodeByteVector3(t.X, t.Y, t.Z)))
            Next
        End If
        Return result
    End Function

    Public Function GetUVs() As List(Of TexCoord) Implements IShapeGeometry.GetUVs
        If Not _tri.HasUVs Then Return New List(Of TexCoord)()
        Return If(_tri.UVs?.ToList(), New List(Of TexCoord)())
    End Function

    Public Function GetVertexColors() As List(Of Color4) Implements IShapeGeometry.GetVertexColors
        If Not _tri.HasVertexColors Then Return New List(Of Color4)()
        Return If(_tri.VertexColors?.ToList(), New List(Of Color4)())
    End Function

    Public Function GetEyeData() As List(Of Single) Implements IShapeGeometry.GetEyeData
        If Not _tri.HasEyeData Then Return New List(Of Single)()
        Return If(_tri.EyeData?.ToList(), New List(Of Single)())
    End Function

    Public Function GetTriangles() As List(Of Triangle) Implements IShapeGeometry.GetTriangles
        Return If(_tri.Triangles?.ToList(), New List(Of Triangle)())
    End Function

    ''' <summary>
    ''' Per-vertex bone indices/weights.  Always 4 slots per vertex (NiflySharp's BSVertexData
    ''' BoneWeights/BoneIndices arrays are length 4).  Unused slots have weight=0 and index=0.
    ''' Returns ShapeSkinningData.Empty when the shape is unskinned.
    ''' </summary>
    Public Function GetSkinning() As ShapeSkinningData Implements IShapeGeometry.GetSkinning
        If Not _tri.IsSkinned Then Return ShapeSkinningData.Empty

        Dim n As Integer = _tri.VertexCount
        Const wpv As Integer = 4
        Dim outIdx(n * wpv - 1) As Byte
        Dim outWgt(n * wpv - 1) As SysHalf

        ' BSVertexData/BSVertexDataSSE hold BoneWeights/BoneIndices as [InlineArray(4)]
        ' structs. BoneInlineArrayExt copies the 4 struct slots straight into the
        ' destination slice - no intermediate buffer, one memcopy per field per vertex.
        If Version.IsSSE Then
            Dim vd = _tri.VertexDataSSE
            If vd Is Nothing OrElse vd.Count <> n Then Return ShapeSkinningData.Empty
            For i = 0 To n - 1
                Dim v = vd(i)
                v.BoneIndices.CopyTo(outIdx, i * wpv, wpv)
                v.BoneWeights.CopyTo(outWgt, i * wpv, wpv)
            Next
        Else
            Dim vd = _tri.VertexData
            If vd Is Nothing OrElse vd.Count <> n Then Return ShapeSkinningData.Empty
            For i = 0 To n - 1
                Dim v = vd(i)
                v.BoneIndices.CopyTo(outIdx, i * wpv, wpv)
                v.BoneWeights.CopyTo(outWgt, i * wpv, wpv)
            Next
        End If

        Return New ShapeSkinningData With {
            .BoneIndices = outIdx,
            .BoneWeights = outWgt,
            .WeightsPerVertex = wpv,
            .VertexCount = n,
            .BoneRefIndices = ResolveBonePalette()
        }
    End Function

    ' ─────────────── Write ───────────────
    ''' <summary>
    ''' Establishes the vertex count on the underlying BSTriShape.  No-op if already at
    ''' the requested size.  Otherwise replaces the packed BSVertexData/BSVertexDataSSE
    ''' list with a fresh zero-initialised list of the new size via NiflySharp's
    ''' SetVertexData / SetVertexDataSSE (which sets _numVertices and resizes the
    ''' internal buffer atomically).  After this the per-field setters (SetVertexPositions,
    ''' SetNormals, SetTangents, SetBitangents, SetUVs, SetVertexColors, SetEyeData,
    ''' SetSkinning) are valid to call — each writes into its field of the packed structs.
    '''
    ''' NiflySharp SetVertexData contract (BSTriShape.cs:357-375): sets _numVertices =
    ''' list.Count, Resize(_vertexData_List_BSVD(SSE)) to match, CopyTo(). If list.Count >
    ''' ushort.MaxValue it returns silently — we pre-check here and throw explicitly.
    ''' </summary>
    Public Sub ResizeVertices(vertexCount As Integer) Implements IShapeGeometry.ResizeVertices
        If vertexCount < 0 Then Throw New ArgumentOutOfRangeException(NameOf(vertexCount), "Negative vertex count")
        If vertexCount > UShort.MaxValue Then
            Throw New InvalidOperationException(
                $"ResizeVertices: {vertexCount} exceeds NiflySharp BSTriShape _numVertices UShort limit " &
                "(65535).  BSTriShape cannot hold more than 65535 vertices per shape — split the shape first.")
        End If
        If _tri.VertexCount = vertexCount Then Return

        If Version.IsSSE Then
            Dim fresh As New List(Of BSVertexDataSSE)(vertexCount)
            For i = 0 To vertexCount - 1 : fresh.Add(New BSVertexDataSSE()) : Next
            _tri.SetVertexDataSSE(fresh)
        Else
            Dim fresh As New List(Of BSVertexData)(vertexCount)
            For i = 0 To vertexCount - 1 : fresh.Add(New BSVertexData()) : Next
            _tri.SetVertexData(fresh)
        End If
        SyncDynamicIfNeeded()
    End Sub

    Public Sub SetVertexPositions(positions As List(Of SysNumerics.Vector3)) Implements IShapeGeometry.SetVertexPositions
        _tri.SetVertexPositions(positions)
        SyncDynamicIfNeeded()
    End Sub

    Public Sub SetNormals(normals As List(Of SysNumerics.Vector3)) Implements IShapeGeometry.SetNormals
        _tri.SetNormals(normals)
    End Sub

    ''' <summary>
    ''' Writes renderer-convention tangents back to the NIF.  Per the INVERTIDAS swap, this
    ''' routes to NiflySharp's tri.SetBitangents (which writes BSVertexData.BitangentX/Y/Z,
    ''' selecting full-precision vs half-precision automatically).
    ''' </summary>
    Public Sub SetTangents(tangents As List(Of SysNumerics.Vector3)) Implements IShapeGeometry.SetTangents
        _tri.SetBitangents(tangents)
    End Sub

    ''' <summary>
    ''' Writes renderer-convention bitangents back to the NIF.  Per the INVERTIDAS swap, this
    ''' routes to NiflySharp's tri.SetTangents (which writes BSVertexData.Tangent ByteVector3).
    ''' </summary>
    Public Sub SetBitangents(bitangents As List(Of SysNumerics.Vector3)) Implements IShapeGeometry.SetBitangents
        _tri.SetTangents(bitangents)
    End Sub

    Public Sub SetUVs(uvs As List(Of TexCoord)) Implements IShapeGeometry.SetUVs
        ' NiflySharp BSTriShape.SetUVs takes List<Vector3> (U, V, ignored Z).  TexCoord is a
        ' 2-component struct so we project it into a Vector3 with Z=0 — same convention used
        ' in InjectToTrishape today.
        Dim asVec3 As New List(Of SysNumerics.Vector3)(uvs.Count)
        For Each uv In uvs
            asVec3.Add(New SysNumerics.Vector3(uv.U, uv.V, 0))
        Next
        _tri.SetUVs(asVec3)
    End Sub

    Public Sub SetVertexColors(colors As List(Of Color4)) Implements IShapeGeometry.SetVertexColors
        _tri.SetVertexColors(colors)
    End Sub

    Public Sub SetEyeData(eyeData As List(Of Single)) Implements IShapeGeometry.SetEyeData
        _tri.SetEyeData(eyeData)
    End Sub

    Public Sub SetTriangles(triangles As List(Of Triangle)) Implements IShapeGeometry.SetTriangles
        ' Delegates to the provenance-aware overload which handles SyncDynamicIfNeeded
        ' internally (called right after tri.SetTriangles, before any metadata redistribution).
        SetTriangles(triangles, Nothing)
    End Sub

    Public Sub SetTriangles(triangles As List(Of Triangle), provenance As TriangleRemap) Implements IShapeGeometry.SetTriangles
        ' Snapshot OLD metadata BEFORE writing — needed for redistribution because
        ' tri.SetTriangles updates _numTriangles and may invalidate offsets.
        Dim meshLod = TryCast(_tri, BSMeshLODTriShape)
        Dim subIndex = TryCast(_tri, BSSubIndexTriShape)
        Dim oldSegments As List(Of BSGeometrySegmentData) = Nothing
        Dim oldLOD0 As Integer = 0
        Dim oldLOD1 As Integer = 0
        If subIndex IsNot Nothing AndAlso subIndex.Segments IsNot Nothing Then
            oldSegments = subIndex.Segments.ToList()
        End If
        If meshLod IsNot Nothing Then
            oldLOD0 = CInt(meshLod.LOD0Size)
            oldLOD1 = CInt(meshLod.LOD1Size)
        End If

        ' ─── BSMeshLODTriShape: tier-preserving reorder (no longer lossy) ───
        ' Classify each new triangle by which old LOD tier its source fell in, then reorder
        ' the new triangle list so all LOD0 come first, then LOD1, then LOD2.  Write the
        ' reordered triangles to the block and set LOD sizes to the bucket counts.  Triangles
        ' with cross-shape or synthetic provenance default to LOD2 (the fallback "rendered at
        ' all distances" tier).  Preserves the LOD optimization across split/merge/zap instead
        ' of collapsing everything to LOD2 (previous canonical BS-OS behaviour).
        Dim writeTris As List(Of Triangle) = triangles
        Dim newLOD0Count As Integer = 0
        Dim newLOD1Count As Integer = 0
        Dim newLOD2Count As Integer = 0
        If meshLod IsNot Nothing AndAlso provenance IsNot Nothing Then
            Dim reordered = ReorderTrianglesByLODTier(triangles, provenance, oldLOD0, oldLOD1)
            writeTris = reordered.Triangles
            newLOD0Count = reordered.LOD0Count
            newLOD1Count = reordered.LOD1Count
            newLOD2Count = reordered.LOD2Count
        End If

        _tri.SetTriangles(Version, writeTris)
        SyncDynamicIfNeeded()

        ' Redistribute count-derived metadata when caller provided provenance.  Without
        ' provenance the metadata stays as-is (likely stale — caller's responsibility).
        If provenance Is Nothing Then Return

        If meshLod IsNot Nothing Then
            meshLod.LOD0Size = CUInt(newLOD0Count)
            meshLod.LOD1Size = CUInt(newLOD1Count)
            meshLod.LOD2Size = CUInt(newLOD2Count)
            Return
        End If

        ' ─── BSSubIndexTriShape: full Segments + SubSegmentDatas redistribution ───
        ' (BSSubIndex and BSMeshLOD are mutually exclusive — a shape is either one or the
        ' other, never both.  No LOD reorder applied to BSSubIndex triangles.)
        If subIndex IsNot Nothing AndAlso oldSegments IsNot Nothing AndAlso oldSegments.Count > 0 Then
            Dim newSegments = RedistributeSegments(oldSegments, provenance, triangles.Count)
            subIndex.Segments = newSegments
            ' Align the parallel _segmentData (SSF + PerSegmentData records) so the NIF
            ' block stays internally consistent.
            AlignSubIndexSegmentData(subIndex, newSegments)
        End If
    End Sub

    ''' <summary>
    ''' Result of <see cref="ReorderTrianglesByLODTier"/>: triangles reordered into
    ''' [LOD0 tier][LOD1 tier][LOD2 tier] order, plus the count per bucket so the caller can
    ''' set the corresponding <c>LOD0Size</c>/<c>LOD1Size</c>/<c>LOD2Size</c> fields.
    ''' </summary>
    Friend Structure LODReorderResult
        Public Triangles As List(Of Triangle)
        Public LOD0Count As Integer
        Public LOD1Count As Integer
        Public LOD2Count As Integer
    End Structure

    ''' <summary>
    ''' Re-bucket triangles by the LOD tier their OLD index fell in (per provenance), then
    ''' emit them in [LOD0][LOD1][LOD2] order so the shape's <c>LOD0Size/1/2Size</c> fields
    ''' reference contiguous ranges.  Called from <see cref="SetTriangles"/> for
    ''' BSMeshLODTriShape and reused by <c>NiTriShapeGeometry</c> for BSLODTriShape.
    '''
    ''' Classification:
    ''' <list type="bullet">
    '''   <item>Same-shape non-synthetic source (Shape=Nothing, OldIdx≥0) → bucket by old range.</item>
    '''   <item>Cross-shape (Shape IsNot Nothing, e.g. merge donor) → LOD2 (default fallback).</item>
    '''   <item>Synthetic (Shape=Nothing, OldIdx&lt;0) → LOD2.</item>
    ''' </list>
    '''
    ''' LOD2 is the fallback tier because it's "always rendered at all distances" — any
    ''' triangle we can't place in a specific tier stays visible at all LODs, preserving
    ''' geometric correctness at the cost of some LOD optimization for those triangles.
    ''' </summary>
    Friend Shared Function ReorderTrianglesByLODTier(
            triangles As List(Of Triangle),
            provenance As TriangleRemap,
            oldLOD0Size As Integer,
            oldLOD1Size As Integer) As LODReorderResult

        Dim oldLOD0End As Integer = oldLOD0Size
        Dim oldLOD1End As Integer = oldLOD0Size + oldLOD1Size

        Dim bucket0 As New List(Of Triangle)()
        Dim bucket1 As New List(Of Triangle)()
        Dim bucket2 As New List(Of Triangle)(triangles.Count)

        For i = 0 To triangles.Count - 1
            Dim src = provenance.Sources(i)
            Dim tier As Integer = 2  ' default: cross-shape / synthetic → LOD2
            If src.Shape Is Nothing AndAlso src.OldIdx >= 0 Then
                If src.OldIdx < oldLOD0End Then
                    tier = 0
                ElseIf src.OldIdx < oldLOD1End Then
                    tier = 1
                Else
                    tier = 2
                End If
            End If
            Select Case tier
                Case 0 : bucket0.Add(triangles(i))
                Case 1 : bucket1.Add(triangles(i))
                Case Else : bucket2.Add(triangles(i))
            End Select
        Next

        Dim reordered As New List(Of Triangle)(triangles.Count)
        reordered.AddRange(bucket0)
        reordered.AddRange(bucket1)
        reordered.AddRange(bucket2)

        Return New LODReorderResult With {
            .Triangles = reordered,
            .LOD0Count = bucket0.Count,
            .LOD1Count = bucket1.Count,
            .LOD2Count = bucket2.Count
        }
    End Function

    ''' <summary>
    ''' Semantic representation of a BSSubIndexTriShape sub-segment that survives
    ''' triangle-list mutations.  Mirrors nifly's NifSubSegmentInfo (Geometry.hpp:392).
    ''' </summary>
    Public Class NifSubSegmentInfo
        ''' <summary>
        ''' Unique non-negative integer identifying this sub-segment among all parents
        ''' and sub-segments of the shape.  Used as a value in triParts.  Not stored in
        ''' the file.
        ''' </summary>
        Public Property PartID As Integer = 0
        Public Property UserSlotID As UInteger = 0
        Public Property Material As UInteger = &HFFFFFFFFUI
        Public Property ExtraData As New List(Of Single)
    End Class

    ''' <summary>
    ''' Semantic representation of a BSSubIndexTriShape parent segment.  Mirrors nifly's
    ''' NifSegmentInfo (Geometry.hpp:404).
    ''' </summary>
    Public Class NifSegmentInfo
        Public Property PartID As Integer = 0
        Public Property Subs As New List(Of NifSubSegmentInfo)
    End Class

    ''' <summary>
    ''' Semantic representation of an entire BSSubIndexTriShape segmentation.  Mirrors
    ''' nifly's NifSegmentationInfo (Geometry.hpp:416).  The intent: extract segmentation
    ''' as semantic data with stable per-triangle partID assignments, mutate triangles
    ''' arbitrarily (split/merge/zap), then re-apply the segmentation by passing the new
    ''' triParts mapping.  Identical contract to nifly so cross-app behavior matches.
    ''' </summary>
    Public Class NifSegmentationInfo
        Public Property Segs As New List(Of NifSegmentInfo)
        Public Property SsfFile As String = ""
    End Class

    ''' <summary>
    ''' Result of <see cref="GetSegmentation(IShapeGeometry)"/>: semantic segmentation
    ''' info paired with the per-triangle partition map.  Returned as a record so callers
    ''' don't have to deal with VB.NET ByRef-Out parameter idioms.
    ''' </summary>
    Public Structure SegmentationSnapshot
        Public Info As NifSegmentationInfo
        Public TriParts As List(Of Integer)

        ''' <summary>True when the source shape had no segmentation data
        ''' (non-BSSubIndex, or BSSubIndex with zero parent segments).</summary>
        Public ReadOnly Property IsEmpty As Boolean
            Get
                Return Info Is Nothing OrElse Info.Segs.Count = 0
            End Get
        End Property
    End Structure

    ''' <summary>
    ''' Adapter-friendly extraction of BSSubIndexTriShape segmentation as semantic info +
    ''' per-triangle partID assignments.  Returns an empty snapshot if the shape isn't
    ''' BSSubIndex (NiTriShape, plain BSTriShape, BSMeshLOD without dismember).
    ''' </summary>
    Public Shared Function GetSegmentation(geom As IShapeGeometry) As SegmentationSnapshot
        Dim subIndex = TryCast(geom?.BackingShape, BSSubIndexTriShape)
        If subIndex Is Nothing Then
            Return New SegmentationSnapshot With {
                .Info = New NifSegmentationInfo(),
                .TriParts = New List(Of Integer)()
            }
        End If
        Return GetSegmentation(subIndex)
    End Function

    ''' <summary>
    ''' Adapter-friendly application of segmentation info + triParts to a shape.  No-op if
    ''' the shape isn't BSSubIndex.  Mutates Segments + SegmentData atomically — see the
    ''' BSSubIndexTriShape overload below for the full algorithm.
    ''' </summary>
    Public Shared Sub SetSegmentation(geom As IShapeGeometry,
                                       inf As NifSegmentationInfo,
                                       inTriParts As List(Of Integer))
        Dim subIndex = TryCast(geom?.BackingShape, BSSubIndexTriShape)
        If subIndex Is Nothing Then Return
        SetSegmentation(subIndex, inf, inTriParts, geom.Version)
    End Sub

    ''' <summary>
    ''' Extracts BSSubIndexTriShape segmentation as semantic info + per-triangle partID
    ''' assignments.  Replicates BS-OS Geometry.cpp:1365-1406
    ''' (BSSubIndexTriShape::GetSegmentation) line-by-line.
    '''
    ''' Walks Segments[] in order; for each parent segment populates triParts[id] for
    ''' triangles in [startIndex/3, startIndex/3 + numPrimitives) with a fresh partID,
    ''' then for each sub-segment of that parent does the same with the next partID.
    ''' arrayIndex tracks the position in the flat PerSegmentData array (parent slot +
    ''' child slots) so userSlotID / material / extraData can be pulled into NifSubSegmentInfo.
    ''' </summary>
    Public Shared Function GetSegmentation(subIndex As BSSubIndexTriShape) As SegmentationSnapshot
        Dim result As New SegmentationSnapshot With {
            .Info = New NifSegmentationInfo(),
            .TriParts = New List(Of Integer)()
        }

        Dim sd As BSGeometrySegmentSharedData = subIndex.SegmentData
        If sd.SSFFile IsNot Nothing Then result.Info.SsfFile = If(sd.SSFFile.Content, "")

        Dim segments = subIndex.Segments
        If segments IsNot Nothing Then
            For si = 0 To segments.Count - 1
                result.Info.Segs.Add(New NifSegmentInfo())
            Next
        End If

        Dim numTris As Integer = subIndex.TriangleCount
        result.TriParts.Capacity = numTris
        For k = 0 To numTris - 1 : result.TriParts.Add(-1) : Next

        If segments Is Nothing Then Return result

        Dim partID As Integer = 0
        Dim arrayIndex As Integer = 0

        For si = 0 To segments.Count - 1
            Dim seg = segments(si)
            Dim startIndex As Integer = CInt(seg.StartIndex \ 3UI)
            Dim endIndex As Integer = Math.Min(numTris, startIndex + CInt(seg.NumPrimitives))

            For id = startIndex To endIndex - 1
                result.TriParts(id) = partID
            Next

            result.Info.Segs(si).PartID = partID
            partID += 1

            Dim subs = seg.SubSegment
            If subs IsNot Nothing AndAlso subs.Count > 0 Then
                For j = 0 To subs.Count - 1
                    Dim sub_ = subs(j)
                    startIndex = CInt(sub_.StartIndex \ 3UI)
                    endIndex = Math.Min(numTris, startIndex + CInt(sub_.NumPrimitives))
                    For id = startIndex To endIndex - 1
                        result.TriParts(id) = partID
                    Next

                    Dim subInfo As New NifSubSegmentInfo() With {.PartID = partID}
                    partID += 1
                    arrayIndex += 1

                    ' Pull metadata from PerSegmentData at arrayIndex.  BS-OS
                    ' Geometry.cpp:1399-1402 reads at arrayIndex (post-increment); we
                    ' replicate exactly.  If PerSegmentData is malformed (size inconsistent
                    ' with parent+child layout) the next line throws on bounds — corrupt
                    ' input must surface, not be hidden.
                    Dim rec = sd.PerSegmentData(arrayIndex)
                    ' BS-OS clamps userSlotID < 30 to 0 on read (Geometry.cpp:1400).
                    ' Replicate the same clamp so round-trips preserve canonical values.
                    subInfo.UserSlotID = If(rec.UserIndex < 30UI, 0UI, rec.UserIndex)
                    subInfo.Material = rec.BoneID
                    If rec.CutOffsets IsNot Nothing Then
                        subInfo.ExtraData = New List(Of Single)(rec.CutOffsets)
                    End If
                    result.Info.Segs(si).Subs.Add(subInfo)
                Next
            End If
            arrayIndex += 1
        Next

        Return result
    End Function

    ''' <summary>
    ''' Reconstructs BSSubIndexTriShape segmentation from semantic info + per-triangle
    ''' partID assignments.  Replicates BS-OS Geometry.cpp:1408-1514
    ''' (BSSubIndexTriShape::SetSegmentation) line-by-line.
    '''
    ''' Algorithm: renumber partIDs to be monotonically increasing in the order parent /
    ''' child appears in inf, sort triangle indices by partID (stable), compute partTriInds
    ''' (start triangle index per partition), build segments + dataRecords + arrayIndices
    ''' from inf.  Triangles get reordered to match the partition order (stable sort) so
    ''' the final StartIndex / NumPrimitives ranges are contiguous per partition.
    '''
    ''' Authoritative entry point — mutates Segments + SegmentData atomically via the
    ''' public NiflySharp setters (no reflection), never leaves a stale combination that
    ''' would corrupt PerSegmentData when NiflySharp's Sync resizes against an out-of-date
    ''' NumSegments / TotalSegments.
    ''' </summary>
    Public Shared Sub SetSegmentation(subIndex As BSSubIndexTriShape,
                                       inf As NifSegmentationInfo,
                                       inTriParts As List(Of Integer),
                                       nifVersion As NiVersion)
        Dim numTris As Integer = subIndex.TriangleCount
        If inTriParts.Count <> numTris Then
            Throw New ArgumentException(
                $"inTriParts size ({inTriParts.Count}) must match shape triangle count ({numTris}).")
        End If

        ' Renumber partition IDs so they're monotonically increasing in inf order
        ' (Geometry.cpp:1413-1426).
        Dim newPartID As Integer = 0
        Dim oldToNewPartIDs As New List(Of Integer)()
        For Each seg In inf.Segs
            EnsureCapacity(oldToNewPartIDs, seg.PartID + 1)
            oldToNewPartIDs(seg.PartID) = newPartID
            newPartID += 1
            For Each sub_ In seg.Subs
                EnsureCapacity(oldToNewPartIDs, sub_.PartID + 1)
                oldToNewPartIDs(sub_.PartID) = newPartID
                newPartID += 1
            Next
        Next

        Dim triParts As Integer() = New Integer(numTris - 1) {}
        For i = 0 To numTris - 1
            If inTriParts(i) >= 0 Then
                triParts(i) = oldToNewPartIDs(inTriParts(i))
            End If
        Next

        ' Sort triangle indices by partition ID (stable) — Geometry.cpp:1433-1442.
        Dim triInds As Integer() = New Integer(numTris - 1) {}
        For i = 0 To numTris - 1 : triInds(i) = i : Next
        Array.Sort(triInds, Function(a, b) triParts(a).CompareTo(triParts(b)))

        ' Reorder triangles in the shape to match the new partition order.
        Dim oldTris = subIndex.Triangles
        Dim newTris As New List(Of Triangle)(numTris)
        For i = 0 To numTris - 1
            newTris.Add(oldTris(triInds(i)))
        Next
        subIndex.SetTriangles(nifVersion, newTris)

        ' Find first triangle of each partition: partTriInds[p] = index of first triangle
        ' of partition p (Geometry.cpp:1452-1458).
        Dim partTriInds As Integer() = New Integer(newPartID) {}
        Dim nextPartID As Integer = 0
        For i = 0 To numTris - 1
            Do While triParts(triInds(i)) >= nextPartID
                partTriInds(nextPartID) = i
                nextPartID += 1
            Loop
        Next
        Do While nextPartID <= newPartID
            partTriInds(nextPartID) = numTris
            nextPartID += 1
        Loop

        ' Build segments + PerSegmentData + arrayIndices in canonical interleaved order
        ' (Geometry.cpp:1460-1506).
        Dim newSegments As New List(Of BSGeometrySegmentData)()
        Dim newPerSegmentData As New List(Of BSGeometryPerSegmentSharedData)()
        Dim arrayIndices As New List(Of UInteger)()
        Dim parentArrayIndex As UInteger = 0
        Dim segmentIndex As UInteger = 0
        Dim partID As Integer = 0

        For Each seg In inf.Segs
            Dim childCount As Integer = seg.Subs.Count
            Dim segNumPrim As Integer = partTriInds(partID + childCount + 1) - partTriInds(partID)
            Dim segStartIndex As UInteger = CUInt(partTriInds(partID)) * 3UI

            Dim newSeg As New BSGeometrySegmentData() With {
                .Flags = 0,
                .StartIndex = segStartIndex,
                .NumPrimitives = CUInt(segNumPrim),
                .ParentArrayIndex = &HFFFFFFFFUI,
                .NumSubSegments = CUInt(childCount),
                .SubSegment = New List(Of BSGeometrySubSegment)(childCount)
            }
            partID += 1

            ' Parent dataRecord — Geometry.cpp:1476-1479: userSlotID = segmentIndex,
            ' material = 0xFFFFFFFF (default), no extraData.
            newPerSegmentData.Add(New BSGeometryPerSegmentSharedData() With {
                .UserIndex = segmentIndex,
                .BoneID = &HFFFFFFFFUI,
                .NumCutOffsets = 0UI,
                .CutOffsets = New List(Of Single)()
            })
            arrayIndices.Add(parentArrayIndex)

            Dim subSegmentNumber As UInteger = 1UI
            For Each sub_ In seg.Subs
                Dim subNumPrim As Integer = partTriInds(partID + 1) - partTriInds(partID)
                Dim subStartIndex As UInteger = CUInt(partTriInds(partID)) * 3UI

                newSeg.SubSegment.Add(New BSGeometrySubSegment() With {
                    .StartIndex = subStartIndex,
                    .NumPrimitives = CUInt(subNumPrim),
                    .ParentArrayIndex = parentArrayIndex,
                    .Unused = 0UI
                })
                partID += 1

                ' Sub dataRecord — Geometry.cpp:1492-1501: userSlotID gets renumbered to
                ' subSegmentNumber if the original was < 30 (canonical body-part slot
                ' range), otherwise preserved as-is.
                Dim subUserSlot As UInteger
                If sub_.UserSlotID < 30UI Then
                    subUserSlot = subSegmentNumber
                    subSegmentNumber += 1UI
                Else
                    subUserSlot = sub_.UserSlotID
                End If

                Dim cutOffsets As New List(Of Single)(If(sub_.ExtraData, New List(Of Single)))
                newPerSegmentData.Add(New BSGeometryPerSegmentSharedData() With {
                    .UserIndex = subUserSlot,
                    .BoneID = sub_.Material,
                    .NumCutOffsets = CUInt(cutOffsets.Count),
                    .CutOffsets = cutOffsets
                })
            Next

            newSegments.Add(newSeg)
            parentArrayIndex += CUInt(childCount) + 1UI
            segmentIndex += 1UI
        Next

        ' Atomic write-back via NiflySharp's public SegmentData property
        ' (BSSubIndexTriShape.cs:10).  No reflection needed — the property's setter writes
        ' the struct value directly into _segmentData.
        Dim sd As BSGeometrySegmentSharedData = subIndex.SegmentData
        sd.NumSegments = CUInt(newSegments.Count)
        sd.TotalSegments = parentArrayIndex
        sd.SegmentStarts = arrayIndices
        sd.PerSegmentData = newPerSegmentData
        ' SSFFile preserved unless caller supplied one in inf.
        If Not String.IsNullOrEmpty(inf.SsfFile) Then
            If sd.SSFFile Is Nothing Then sd.SSFFile = New NiString2()
            sd.SSFFile.Content = inf.SsfFile
        End If
        subIndex.SegmentData = sd
        subIndex.Segments = newSegments
    End Sub

    ''' <summary>
    ''' Internal preserve-policy update used by <see cref="SetTriangles"/> after
    ''' RedistributeSegments produces a list with the same structural count as the
    ''' original (zap and split paths — RedistributeSegments preserves parent and
    ''' subSegment counts even when individual NumPrimitives drop to 0).  Updates only
    ''' count-derived fields and SegmentStarts; preserves PerSegmentData and SSFFile.
    '''
    ''' Fast path for zap/split where the structural layout is invariant.  Merge uses
    ''' the full <see cref="GetSegmentation"/>/<see cref="SetSegmentation"/> round-trip
    ''' instead because parent and sub counts grow.
    '''
    ''' Always rewrites SegmentStarts as cumulative parentArrayIndex per BS-OS
    ''' Geometry.cpp:1478/1504 (parentArrayIndex += childCount + 1 between iterations).
    ''' </summary>
    Private Shared Sub AlignSubIndexSegmentData(subIndex As BSSubIndexTriShape, newSegments As List(Of BSGeometrySegmentData))
        Dim sd As BSGeometrySegmentSharedData = subIndex.SegmentData

        Dim totalSubSegments As UInteger = 0
        Dim starts As New List(Of UInteger)(newSegments.Count)
        Dim parentArrayIndex As UInteger = 0
        For Each seg In newSegments
            starts.Add(parentArrayIndex)
            Dim childCount As UInteger = CUInt(If(seg.SubSegment Is Nothing, 0, seg.SubSegment.Count))
            parentArrayIndex += childCount + 1UI
            totalSubSegments += childCount
        Next
        Dim newTotal As UInteger = CUInt(newSegments.Count) + totalSubSegments

        If sd.PerSegmentData IsNot Nothing AndAlso sd.PerSegmentData.Count <> CInt(newTotal) Then
            Throw New InvalidOperationException(
                $"AlignSubIndexSegmentData preserve-policy invariant violated: existing " &
                $"PerSegmentData count ({sd.PerSegmentData.Count}) differs from new total ({newTotal}).  " &
                "RedistributeSegments must preserve parent and sub-segment counts in this code path; " &
                "if counts change, route the update through SetSegmentation instead.")
        End If

        sd.NumSegments = CUInt(newSegments.Count)
        sd.TotalSegments = newTotal
        sd.SegmentStarts = starts

        subIndex.SegmentData = sd
    End Sub

    ''' <summary>
    ''' Grows <paramref name="list"/> with default values until its Count is at least
    ''' <paramref name="minCount"/>.  Local helper so SetSegmentation's partID renumber
    ''' loop reads cleaner than the Do/Loop While idiom that VB.NET requires for
    ''' incremental capacity expansion.
    ''' </summary>
    Private Shared Sub EnsureCapacity(list As List(Of Integer), minCount As Integer)
        Do While list.Count < minCount
            list.Add(0)
        Loop
    End Sub

    ''' <summary>
    ''' Rebuilds a BSGeometrySegmentData list after a triangle-count change.  For each
    ''' old segment, counts how many new triangles came from its [StartIndex/3,
    ''' StartIndex/3 + NumPrimitives) range using <paramref name="provenance"/>.  Realigns
    ''' the StartIndex of each new segment to be cumulative (previous.StartIndex +
    ''' previous.NumPrimitives * 3) — same convention BS-OS uses (Geometry.cpp:1289).
    ''' SubSegmentDatas within each segment get the same treatment recursively.
    '''
    ''' Triangle-order assumption: this algorithm assumes that the new triangle list
    ''' preserves the relative order of triangles within each old segment (i.e. survivors
    ''' from old segment N still come before survivors from old segment N+1).  Zap and
    ''' split satisfy this trivially (filter preserves order).  Merge populates segments
    ''' via append rather than this algorithm so the assumption isn't tested there.
    ''' </summary>
    ''' <summary>
    ''' Friend visibility: NiTriShapeGeometry.BSSegmentedTriShape branch reuses this exact
    ''' redistribution logic (BSSegmented uses the same BSGeometrySegmentData struct, just
    ''' on a different host class).  Keeping a single implementation avoids drift between
    ''' the two shape families.
    ''' </summary>
    Friend Shared Function RedistributeSegments(oldSegments As List(Of BSGeometrySegmentData),
                                                  provenance As TriangleRemap,
                                                  newTriCount As Integer) As List(Of BSGeometrySegmentData)
        Dim result As New List(Of BSGeometrySegmentData)(oldSegments.Count)
        Dim cumulativeTriIdx As Integer = 0

        ' ─── Phase 1: index provenance by old triangle idx — O(N) ───
        ' Build a map oldTriIdx → count of new survivors coming from that old idx.  Also
        ' count synthetic entries (Shape=Nothing AND OldIdx<0) in one pass for the fallback
        ' segment at the end.  Previously the segment loop did O(N*M) — for each segment it
        ' rescanned all provenance entries.  Dict lookup drops it to O(N + sum of segment
        ' ranges) which is O(N + oldTotal) ≈ O(N + M) for typical NIFs.
        Dim survivorsByOld As New Dictionary(Of Integer, Integer)(provenance.Sources.Count)
        Dim syntheticUncovered As Integer = 0
        For i = 0 To provenance.Sources.Count - 1
            Dim src = provenance.Sources(i)
            If src.Shape IsNot Nothing Then Continue For  ' cross-shape: handled by MergeMetadataAfterApply
            If src.OldIdx < 0 Then
                syntheticUncovered += 1
                Continue For
            End If
            Dim existing As Integer
            If survivorsByOld.TryGetValue(src.OldIdx, existing) Then
                survivorsByOld(src.OldIdx) = existing + 1
            Else
                survivorsByOld(src.OldIdx) = 1
            End If
        Next

        ' ─── Phase 2: emit new segments by scanning each old range — O(oldTotal) ───
        For Each oldSeg In oldSegments
            Dim oldStartTri As Integer = CInt(oldSeg.StartIndex \ 3UI)
            Dim oldEndTri As Integer = oldStartTri + CInt(oldSeg.NumPrimitives)

            Dim survivors As Integer = 0
            For oldIdx = oldStartTri To oldEndTri - 1
                Dim cnt As Integer
                If survivorsByOld.TryGetValue(oldIdx, cnt) Then survivors += cnt
            Next

            Dim newSeg As New BSGeometrySegmentData() With {
                .Flags = oldSeg.Flags,
                .StartIndex = CUInt(cumulativeTriIdx) * 3UI,
                .NumPrimitives = CUInt(survivors),
                .ParentArrayIndex = oldSeg.ParentArrayIndex
            }

            ' SubSegments: same algorithm, scoped to the parent segment range, reuses the
            ' survivorsByOld dict (already built) so each sub-seg is O(subRange) — no N rescan.
            If oldSeg.SubSegment IsNot Nothing AndAlso oldSeg.SubSegment.Count > 0 Then
                newSeg.SubSegment = RedistributeSubSegments(oldSeg.SubSegment, survivorsByOld, CInt(newSeg.StartIndex \ 3UI))
                newSeg.NumSubSegments = CUInt(newSeg.SubSegment.Count)
            Else
                newSeg.SubSegment = New List(Of BSGeometrySubSegment)()
                newSeg.NumSubSegments = 0UI
            End If

            result.Add(newSeg)
            cumulativeTriIdx += survivors
        Next

        ' Runtime validation (was Debug.Assert — upgraded to hard throw so release builds
        ' also catch malformed provenance before the NIF gets written with inconsistent
        ' segment ranges that would make the game read out-of-bounds triangles).
        If cumulativeTriIdx > newTriCount Then
            Throw New InvalidOperationException(
                $"RedistributeSegments: cumulative survivors ({cumulativeTriIdx}) exceeds new triangle " &
                $"count ({newTriCount}).  Provenance map is malformed (duplicate oldIdx entries or " &
                "oldIdx values outside original triangle range).  Refusing to produce a segmented NIF " &
                "that would be read out-of-bounds by the dismember engine.")
        End If

        ' Synthetic-only fallback: new triangles with (Shape=Nothing AND OldIdx<0) are
        ' synthetic entries in same-shape provenance (e.g. a future caller that appends
        ' generated triangles to an existing shape).  Bundle those into a catch-all segment
        ' so the shape stays dismember-legal.  Cross-shape entries are NOT covered here —
        ' MergeShapesHelper.MergeMetadataAfterApply appends donor segments with proper
        ' offset; emitting a fallback + donor-append would double-count (PrimSum > TC bug
        ' caught by ShapeTypeValidator test C).
        If syntheticUncovered > 0 AndAlso cumulativeTriIdx + syntheticUncovered <= newTriCount Then
            Dim fallback As New BSGeometrySegmentData() With {
                .Flags = 0,
                .StartIndex = CUInt(cumulativeTriIdx) * 3UI,
                .NumPrimitives = CUInt(syntheticUncovered),
                .ParentArrayIndex = UInteger.MaxValue,  ' "no parent" sentinel (matches BS-OS SetDefaultSegments convention)
                .NumSubSegments = 0UI,
                .SubSegment = New List(Of BSGeometrySubSegment)()
            }
            result.Add(fallback)
        End If

        Return result
    End Function

    ''' <summary>
    ''' Same redistribution algorithm as <see cref="RedistributeSegments"/> but for the
    ''' sub-segment list of a single parent segment.  StartIndex of each new sub-segment is
    ''' cumulative starting from <paramref name="newParentStartTri"/> (in triangle units —
    ''' multiplied by 3 for storage as vertex-index units).
    ''' </summary>
    ''' <summary>
    ''' Sub-segment redistribution.  Signature differs from the public overload by accepting
    ''' the pre-built <paramref name="survivorsByOld"/> dictionary instead of walking
    ''' provenance again — the outer <see cref="RedistributeSegments"/> builds that dict
    ''' once and reuses it across all parent segments and their sub-segments.  Each sub-seg
    ''' is then O(subRange) instead of O(N).
    ''' </summary>
    Private Shared Function RedistributeSubSegments(oldSubSegments As List(Of BSGeometrySubSegment),
                                                     survivorsByOld As Dictionary(Of Integer, Integer),
                                                     newParentStartTri As Integer) As List(Of BSGeometrySubSegment)
        Dim result As New List(Of BSGeometrySubSegment)(oldSubSegments.Count)
        Dim cumulativeTriIdx As Integer = newParentStartTri

        For Each oldSub In oldSubSegments
            Dim oldStartTri As Integer = CInt(oldSub.StartIndex \ 3UI)
            Dim oldEndTri As Integer = oldStartTri + CInt(oldSub.NumPrimitives)

            Dim survivors As Integer = 0
            For oldIdx = oldStartTri To oldEndTri - 1
                Dim cnt As Integer
                If survivorsByOld.TryGetValue(oldIdx, cnt) Then survivors += cnt
            Next

            result.Add(New BSGeometrySubSegment() With {
                .StartIndex = CUInt(cumulativeTriIdx) * 3UI,
                .NumPrimitives = CUInt(survivors),
                .ParentArrayIndex = oldSub.ParentArrayIndex,
                .Unused = oldSub.Unused
            })
            cumulativeTriIdx += survivors
        Next

        Return result
    End Function

    Public Sub UpdateBounds() Implements IShapeGeometry.UpdateBounds
        _tri.UpdateBounds()
    End Sub

    ''' <summary>
    ''' Writes per-vertex bone influences into BSVertexData[].BoneIndices / BoneWeights
    ''' (FO4) or BSVertexDataSSE[].BoneIndices / BoneWeights (SSE).  Length of the packed
    ''' list and <paramref name="skinning"/>.VertexCount must match.  Each vertex's 4 slots
    ''' are written in order; missing slots in the input default to (idx=0, weight=0).
    ''' </summary>
    Public Sub SetSkinning(skinning As ShapeSkinningData) Implements IShapeGeometry.SetSkinning
        If skinning.BoneIndices Is Nothing OrElse skinning.BoneWeights Is Nothing Then Return
        Dim n As Integer = _tri.VertexCount
        If skinning.VertexCount <> n Then
            Debug.Assert(False, $"SetSkinning vertex count mismatch: shape has {n}, skinning has {skinning.VertexCount}")
            Return
        End If
        Const wpv As Integer = 4
        Dim inputWpv As Integer = If(skinning.WeightsPerVertex > 0, skinning.WeightsPerVertex, wpv)

        ' Copy directly from the input slice into each vertex's [InlineArray(4)] structs.
        ' Inputs wider than 4 are truncated; shorter inputs leave trailing slots at zero
        ' (the struct is reset to default before CopyFrom so prior contents don't bleed through).
        Dim copy As Integer = Math.Min(wpv, inputWpv)
        If Version.IsSSE Then
            Dim vd = _tri.VertexDataSSE
            If vd Is Nothing OrElse vd.Count <> n Then Return
            For i = 0 To n - 1
                Dim v = vd(i)   ' struct copy (BSVertexDataSSE is a struct)
                ' Extract bone fields to direct locals before CopyFrom: VB.NET cannot guarantee
                ' that ByRef-Me extensions over a NESTED struct field of a local target the
                ' original field (silent temp-copy drops the write). With top-level locals the
                ' ByRef is unambiguous. The locals start zero-initialised so slots beyond `copy`
                ' (when inputWpv < 4) end up at zero without an extra padding pass.
                Dim bi As BoneIndices4
                Dim bw As BoneWeights4
                bi.CopyFrom(skinning.BoneIndices, i * inputWpv, copy)
                bw.CopyFrom(skinning.BoneWeights, i * inputWpv, copy)
                v.BoneIndices = bi
                v.BoneWeights = bw
                vd(i) = v   ' write back the modified struct
            Next
        Else
            Dim vd = _tri.VertexData
            If vd Is Nothing OrElse vd.Count <> n Then Return
            For i = 0 To n - 1
                Dim v = vd(i)
                ' See comment in the SSE branch above — same nested-ByRef caveat.
                Dim bi As BoneIndices4
                Dim bw As BoneWeights4
                bi.CopyFrom(skinning.BoneIndices, i * inputWpv, copy)
                bw.CopyFrom(skinning.BoneWeights, i * inputWpv, copy)
                v.BoneIndices = bi
                v.BoneWeights = bw
                vd(i) = v
            Next
        End If
        ' BSDynamicTriShape safety: CalcDynamicData() re-syncs the parallel Vector4 _vertices
        ' buffer (carries BitangentX in W).  SetSkinning only mutates BoneIndices/BoneWeights,
        ' which don't affect _vertices, but call SyncDynamicIfNeeded defensively so every
        ' write path on BSTriShapeGeometry leaves the dynamic buffer coherent.
        SyncDynamicIfNeeded()
    End Sub

    ' ─────────────── Helpers ───────────────
    Private Shared Function DecodeBitangent(x As Single, by As SByte, bz As SByte) As SysNumerics.Vector3
        Dim yf As Single = (CInt(by) And &HFF) / 255.0F * 2.0F - 1.0F
        Dim zf As Single = (CInt(bz) And &HFF) / 255.0F * 2.0F - 1.0F
        Return NormalizeOrZero(New SysNumerics.Vector3(x, yf, zf))
    End Function

    Private Shared Function DecodeByteVector3(x As SByte, y As SByte, z As SByte) As SysNumerics.Vector3
        Dim xf As Single = (CInt(x) And &HFF) / 255.0F * 2.0F - 1.0F
        Dim yf As Single = (CInt(y) And &HFF) / 255.0F * 2.0F - 1.0F
        Dim zf As Single = (CInt(z) And &HFF) / 255.0F * 2.0F - 1.0F
        Return New SysNumerics.Vector3(xf, yf, zf)
    End Function

    Private Shared Function NormalizeOrZero(v As SysNumerics.Vector3) As SysNumerics.Vector3
        Dim len As Single = v.Length()
        If len > 0.000001F Then Return v / len
        Return SysNumerics.Vector3.Zero
    End Function

    ''' <summary>
    ''' BSDynamicTriShape carries a parallel List(Of Vector4) Vertices field (XYZ position + W
    ''' carrying BitangentX) that is read at runtime by the cloth/dynamic system.  After any
    ''' mutation of the inline BSVertexData positions, that parallel buffer must be re-synced
    ''' via CalcDynamicData() — otherwise the saved NIF carries stale dynamic data even though
    ''' the static positions are correct.  No-op for plain BSTriShape and other subclasses.
    ''' </summary>
    Private Sub SyncDynamicIfNeeded()
        Dim dyn = TryCast(_tri, BSDynamicTriShape)
        If dyn IsNot Nothing Then dyn.CalcDynamicData()
    End Sub

    ''' <summary>
    ''' Copies up to <paramref name="wpv"/> bone influence slots from a single BSVertexData
    ''' vertex into the flat output arrays at vertex offset <paramref name="vIdx"/>.  Pads
    ''' missing slots with index=0, weight=0 — same convention as ShapeSkinningData.Empty.
    ''' </summary>
    ' CopyVertexInfluences helper removed: the two callers (GetSkinning) now iterate
    ' directly over BoneIndices4/BoneWeights4 InlineArray structs without going through
    ' temporary Byte()/SysHalf() arrays.

    ''' <summary>
    ''' Reads the bone-palette block indices from the shape's skin instance Bones reference list.
    ''' Returns an empty array when the skin instance is missing or has no bones.  Pure
    ''' diagnostics — the renderer does not consume this; ShapeBones on IRenderableShape is the
    ''' authoritative source for matrices.
    ''' </summary>
    Private Function ResolveBonePalette() As Integer()
        If _tri.SkinInstanceRef Is Nothing OrElse _tri.SkinInstanceRef.Index = -1 Then Return Array.Empty(Of Integer)()
        If _tri.SkinInstanceRef.Index >= _nif.Blocks.Count Then Return Array.Empty(Of Integer)()
        Dim skinInst = TryCast(_nif.Blocks(_tri.SkinInstanceRef.Index), INiSkin)
        If skinInst Is Nothing OrElse skinInst.Bones Is Nothing Then Return Array.Empty(Of Integer)()
        Return skinInst.Bones.Indices.Select(Function(i) CInt(i)).ToArray()
    End Function
End Class
