Imports NiflySharp
Imports NiflySharp.Blocks
Imports NiflySharp.Structs
Imports SysHalf = System.Half
Imports SysNumerics = System.Numerics

''' <summary>
''' IShapeGeometry adapter for the BSTriShape family (BSTriShape, BSSubIndexTriShape,
''' BSDynamicTriShape, BSSegmentedTriShape, BSMeshLODTriShape).  Vertex/triangle data lives
''' inline in the BSTriShape block (BSVertexData for FO4, BSVertexDataSSE for SSE), and the
''' skin partition is regenerated by NiflySharp's UpdateSkinPartitions on save — this adapter
''' does NOT touch the partition itself.
'''
''' Tangent / Bitangent semantics (the "INVERTIDAS swap"):
''' BSTriShape stores what the NIF format calls "Tangent" (ByteVector3 sbyte) and
''' "Bitangent" (BitangentX float/half + BitangentY/Z sbyte).  Empirically (Wardrobe_Manager
''' renderer + FO4 shaders) the correct interpretation is:
'''     renderer Tangent   = NIF Bitangent   (BitangentX/Y/Z)
'''     renderer Bitangent = NIF Tangent     (Tangent ByteVector3)
''' This adapter encapsulates that swap.  GetTangents/GetBitangents return the renderer-side
''' values; SetTangents/SetBitangents accept renderer-side values and route them back to the
''' opposite NIF field.  Callers never see the swap.
'''
''' Half-precision detail: when the BSTriShape is FO4 half-precision the renderer-side bitangent
''' (NIF Tangent) must be read directly from BSVertexData.Tangent rather than through
''' tri.Tangents — the NiflySharp Vector3 getter has a known decode mismatch for that path.
''' SSE and FO4 full-precision use tri.Tangents normally.
''' </summary>
Public Class BSTriShapeGeometry
    Implements IShapeGeometry

    Private ReadOnly _tri As BSTriShape
    Private ReadOnly _nif As Nifcontent_Class_Manolo

    Public Sub New(tri As BSTriShape, nif As Nifcontent_Class_Manolo)
        If tri Is Nothing Then Throw New ArgumentNullException(NameOf(tri))
        If nif Is Nothing Then Throw New ArgumentNullException(NameOf(nif))
        _tri = tri
        _nif = nif
    End Sub

    ' ─────────────── Identity ───────────────
    Public ReadOnly Property BackingShape As INiShape Implements IShapeGeometry.BackingShape
        Get
            Return _tri
        End Get
    End Property

    Public ReadOnly Property Name As String Implements IShapeGeometry.Name
        Get
            Return If(_tri?.Name?.String, "")
        End Get
    End Property

    Public ReadOnly Property Version As NiVersion Implements IShapeGeometry.Version
        Get
            Return _nif.Header.Version
        End Get
    End Property

    ' ─────────────── Counts and presence ───────────────
    Public ReadOnly Property VertexCount As Integer Implements IShapeGeometry.VertexCount
        Get
            Return _tri.VertexCount
        End Get
    End Property

    Public ReadOnly Property TriangleCount As Integer Implements IShapeGeometry.TriangleCount
        Get
            Return _tri.TriangleCount
        End Get
    End Property

    Public ReadOnly Property HasNormals As Boolean Implements IShapeGeometry.HasNormals
        Get
            Return _tri.HasNormals
        End Get
    End Property

    Public ReadOnly Property HasTangents As Boolean Implements IShapeGeometry.HasTangents
        Get
            Return _tri.HasTangents
        End Get
    End Property

    Public ReadOnly Property HasUVs As Boolean Implements IShapeGeometry.HasUVs
        Get
            Return _tri.HasUVs
        End Get
    End Property

    Public ReadOnly Property HasVertexColors As Boolean Implements IShapeGeometry.HasVertexColors
        Get
            Return _tri.HasVertexColors
        End Get
    End Property

    Public ReadOnly Property HasEyeData As Boolean Implements IShapeGeometry.HasEyeData
        Get
            Return _tri.HasEyeData
        End Get
    End Property

    Public ReadOnly Property IsSkinned As Boolean Implements IShapeGeometry.IsSkinned
        Get
            Return _tri.IsSkinned
        End Get
    End Property

    Public ReadOnly Property Bounds As BoundingSphere Implements IShapeGeometry.Bounds
        Get
            Return _tri.Bounds
        End Get
    End Property

    ' ─────────────── Read ───────────────
    Public Function GetVertexPositions() As List(Of SysNumerics.Vector3) Implements IShapeGeometry.GetVertexPositions
        EnsureNumVerticesSynced()
        Return If(_tri.VertexPositions?.ToList(), New List(Of SysNumerics.Vector3)())
    End Function

    Public Function GetNormals() As List(Of SysNumerics.Vector3) Implements IShapeGeometry.GetNormals
        If Not _tri.HasNormals Then Return New List(Of SysNumerics.Vector3)()
        EnsureNumVerticesSynced()
        Return If(_tri.Normals?.ToList(), New List(Of SysNumerics.Vector3)())
    End Function

    ''' <summary>
    ''' Renderer-convention tangent.  Sourced from NIF "Bitangent" fields (BitangentX/Y/Z)
    ''' due to the INVERTIDAS swap.  Routes by precision: SSE uses BSVertexDataSSE.BitangentX
    ''' (float) + BitangentY/Z (sbyte).  FO4 full-precision uses BSVertexData.BitangentX (float).
    ''' FO4 half-precision uses BSVertexData.BitangentXHalf (Half).  In every case
    ''' BitangentY/Z are sbyte values that decode as ((b And &HFF) / 255 * 2 - 1).
    ''' </summary>
    Public Function GetTangents() As List(Of SysNumerics.Vector3) Implements IShapeGeometry.GetTangents
        If Not _tri.HasTangents Then Return New List(Of SysNumerics.Vector3)()
        Dim n As Integer = _tri.VertexCount
        Dim result As New List(Of SysNumerics.Vector3)(n)

        If Version.IsSSE Then
            Dim vd = _tri.VertexDataSSE
            If vd Is Nothing OrElse vd.Count <> n Then
                ' Defensive: SSE shape with no vertex data — caller would have bigger problems but don't crash here.
                For i = 0 To n - 1 : result.Add(SysNumerics.Vector3.Zero) : Next
                Return result
            End If
            For i = 0 To n - 1
                result.Add(DecodeBitangent(CSng(vd(i).BitangentX), vd(i).BitangentY, vd(i).BitangentZ))
            Next
        Else
            Dim vd = _tri.VertexData
            If vd Is Nothing OrElse vd.Count <> n Then
                For i = 0 To n - 1 : result.Add(SysNumerics.Vector3.Zero) : Next
                Return result
            End If
            If _tri.IsFullPrecision Then
                For i = 0 To n - 1
                    result.Add(DecodeBitangent(vd(i).BitangentX, vd(i).BitangentY, vd(i).BitangentZ))
                Next
            Else
                For i = 0 To n - 1
                    result.Add(DecodeBitangent(CSng(vd(i).BitangentXHalf), vd(i).BitangentY, vd(i).BitangentZ))
                Next
            End If
        End If
        Return result
    End Function

    ''' <summary>
    ''' Renderer-convention bitangent.  Sourced from NIF "Tangent" field (BSVertexData.Tangent
    ''' ByteVector3) due to the INVERTIDAS swap.  For SSE and FO4 full-precision we route
    ''' through tri.Tangents (NiflySharp decodes ByteVector3 → Vector3 correctly there).  For
    ''' FO4 half-precision we read BSVertexData.Tangent directly with the byte normalization,
    ''' to bypass a known NiflySharp Vector3 getter mismatch on that path.
    ''' </summary>
    Public Function GetBitangents() As List(Of SysNumerics.Vector3) Implements IShapeGeometry.GetBitangents
        If Not _tri.HasTangents Then Return New List(Of SysNumerics.Vector3)()
        ' SSE + FO4-full-precision branch below routes through _tri.Tangents → UpdateRawTangents,
        ' which uses the stale _numVertices field — sync before that call.  FO4-half-precision
        ' reads the packed VertexData list directly (via vd.Count check) so sync is redundant
        ' there but harmless.
        EnsureNumVerticesSynced()
        Dim n As Integer = _tri.VertexCount
        Dim result As New List(Of SysNumerics.Vector3)(n)

        If Version.IsSSE OrElse _tri.IsFullPrecision Then
            Dim src = _tri.Tangents
            If src Is Nothing OrElse src.Count <> n Then
                For i = 0 To n - 1 : result.Add(SysNumerics.Vector3.Zero) : Next
                Return result
            End If
            For i = 0 To n - 1
                Dim v = src(i)
                result.Add(NormalizeOrZero(v))
            Next
        Else
            ' FO4 half-precision: read BSVertexData.Tangent (ByteVector3 with sbyte fields) directly.
            Dim vd = _tri.VertexData
            If vd Is Nothing OrElse vd.Count <> n Then
                For i = 0 To n - 1 : result.Add(SysNumerics.Vector3.Zero) : Next
                Return result
            End If
            For i = 0 To n - 1
                Dim t = vd(i).Tangent
                result.Add(NormalizeOrZero(DecodeByteVector3(t.X, t.Y, t.Z)))
            Next
        End If
        Return result
    End Function

    Public Function GetUVs() As List(Of TexCoord) Implements IShapeGeometry.GetUVs
        If Not _tri.HasUVs Then Return New List(Of TexCoord)()
        EnsureNumVerticesSynced()
        Return If(_tri.UVs?.ToList(), New List(Of TexCoord)())
    End Function

    Public Function GetVertexColors() As List(Of Color4) Implements IShapeGeometry.GetVertexColors
        If Not _tri.HasVertexColors Then Return New List(Of Color4)()
        EnsureNumVerticesSynced()
        Return If(_tri.VertexColors?.ToList(), New List(Of Color4)())
    End Function

    Public Function GetEyeData() As List(Of Single) Implements IShapeGeometry.GetEyeData
        If Not _tri.HasEyeData Then Return New List(Of Single)()
        EnsureNumVerticesSynced()
        Return If(_tri.EyeData?.ToList(), New List(Of Single)())
    End Function

    Public Function GetTriangles() As List(Of Triangle) Implements IShapeGeometry.GetTriangles
        Return If(_tri.Triangles?.ToList(), New List(Of Triangle)())
    End Function

    ''' <summary>
    ''' Per-vertex bone indices/weights.  Always 4 slots per vertex (NiflySharp's BSVertexData
    ''' BoneWeights/BoneIndices arrays are length 4).  Unused slots have weight=0 and index=0.
    ''' Returns ShapeSkinningData.Empty when the shape is unskinned.
    ''' </summary>
    Public Function GetSkinning() As ShapeSkinningData Implements IShapeGeometry.GetSkinning
        If Not _tri.IsSkinned Then Return ShapeSkinningData.Empty

        Dim n As Integer = _tri.VertexCount
        Const wpv As Integer = 4
        Dim outIdx(n * wpv - 1) As Byte
        Dim outWgt(n * wpv - 1) As SysHalf

        If Version.IsSSE Then
            Dim vd = _tri.VertexDataSSE
            If vd Is Nothing OrElse vd.Count <> n Then Return ShapeSkinningData.Empty
            For i = 0 To n - 1
                CopyVertexInfluences(vd(i).BoneIndices, vd(i).BoneWeights, outIdx, outWgt, i, wpv)
            Next
        Else
            Dim vd = _tri.VertexData
            If vd Is Nothing OrElse vd.Count <> n Then Return ShapeSkinningData.Empty
            For i = 0 To n - 1
                CopyVertexInfluences(vd(i).BoneIndices, vd(i).BoneWeights, outIdx, outWgt, i, wpv)
            Next
        End If

        Return New ShapeSkinningData With {
            .BoneIndices = outIdx,
            .BoneWeights = outWgt,
            .WeightsPerVertex = wpv,
            .VertexCount = n,
            .BoneRefIndices = ResolveBonePalette()
        }
    End Function

    ' ─────────────── Write ───────────────
    ''' <summary>
    ''' Establishes the vertex count on the underlying BSTriShape.  No-op if already at
    ''' the requested size.  Otherwise replaces the packed BSVertexData/BSVertexDataSSE
    ''' list with a fresh zero-initialised list of the new size via NiflySharp's
    ''' SetVertexData / SetVertexDataSSE (which sets _numVertices and resizes the
    ''' internal buffer atomically).  After this the per-field setters (SetVertexPositions,
    ''' SetNormals, SetTangents, SetBitangents, SetUVs, SetVertexColors, SetEyeData,
    ''' SetSkinning) are valid to call — each writes into its field of the packed structs.
    '''
    ''' NiflySharp SetVertexData contract (BSTriShape.cs:357-375): sets _numVertices =
    ''' list.Count, Resize(_vertexData_List_BSVD(SSE)) to match, CopyTo(). If list.Count >
    ''' ushort.MaxValue it returns silently — we pre-check here and throw explicitly.
    ''' </summary>
    Public Sub ResizeVertices(vertexCount As Integer) Implements IShapeGeometry.ResizeVertices
        If vertexCount < 0 Then Throw New ArgumentOutOfRangeException(NameOf(vertexCount), "Negative vertex count")
        If vertexCount > UShort.MaxValue Then
            Throw New InvalidOperationException(
                $"ResizeVertices: {vertexCount} exceeds NiflySharp BSTriShape _numVertices UShort limit " &
                "(65535).  BSTriShape cannot hold more than 65535 vertices per shape — split the shape first.")
        End If
        If _tri.VertexCount = vertexCount Then Return

        If Version.IsSSE Then
            Dim fresh As New List(Of BSVertexDataSSE)(vertexCount)
            For i = 0 To vertexCount - 1 : fresh.Add(New BSVertexDataSSE()) : Next
            _tri.SetVertexDataSSE(fresh)
        Else
            Dim fresh As New List(Of BSVertexData)(vertexCount)
            For i = 0 To vertexCount - 1 : fresh.Add(New BSVertexData()) : Next
            _tri.SetVertexData(fresh)
        End If
        SyncDynamicIfNeeded()
    End Sub

    Public Sub SetVertexPositions(positions As List(Of SysNumerics.Vector3)) Implements IShapeGeometry.SetVertexPositions
        _tri.SetVertexPositions(positions)
        SyncDynamicIfNeeded()
    End Sub

    Public Sub SetNormals(normals As List(Of SysNumerics.Vector3)) Implements IShapeGeometry.SetNormals
        _tri.SetNormals(normals)
    End Sub

    ''' <summary>
    ''' Writes renderer-convention tangents back to the NIF.  Per the INVERTIDAS swap, this
    ''' routes to NiflySharp's tri.SetBitangents (which writes BSVertexData.BitangentX/Y/Z,
    ''' selecting full-precision vs half-precision automatically).
    ''' </summary>
    Public Sub SetTangents(tangents As List(Of SysNumerics.Vector3)) Implements IShapeGeometry.SetTangents
        _tri.SetBitangents(tangents)
    End Sub

    ''' <summary>
    ''' Writes renderer-convention bitangents back to the NIF.  Per the INVERTIDAS swap, this
    ''' routes to NiflySharp's tri.SetTangents (which writes BSVertexData.Tangent ByteVector3).
    ''' </summary>
    Public Sub SetBitangents(bitangents As List(Of SysNumerics.Vector3)) Implements IShapeGeometry.SetBitangents
        _tri.SetTangents(bitangents)
    End Sub

    Public Sub SetUVs(uvs As List(Of TexCoord)) Implements IShapeGeometry.SetUVs
        ' NiflySharp BSTriShape.SetUVs takes List<Vector3> (U, V, ignored Z).  TexCoord is a
        ' 2-component struct so we project it into a Vector3 with Z=0 — same convention used
        ' in InjectToTrishape today.
        Dim asVec3 As New List(Of SysNumerics.Vector3)(uvs.Count)
        For Each uv In uvs
            asVec3.Add(New SysNumerics.Vector3(uv.U, uv.V, 0))
        Next
        _tri.SetUVs(asVec3)
    End Sub

    Public Sub SetVertexColors(colors As List(Of Color4)) Implements IShapeGeometry.SetVertexColors
        _tri.SetVertexColors(colors)
    End Sub

    Public Sub SetEyeData(eyeData As List(Of Single)) Implements IShapeGeometry.SetEyeData
        _tri.SetEyeData(eyeData)
    End Sub

    Public Sub SetTriangles(triangles As List(Of Triangle)) Implements IShapeGeometry.SetTriangles
        ' Delegates to the provenance-aware overload which handles SyncDynamicIfNeeded
        ' internally (called right after tri.SetTriangles, before any metadata redistribution).
        SetTriangles(triangles, Nothing)
    End Sub

    Public Sub SetTriangles(triangles As List(Of Triangle), provenance As TriangleRemap) Implements IShapeGeometry.SetTriangles
        ' Snapshot OLD metadata BEFORE writing — needed for redistribution because
        ' tri.SetTriangles updates _numTriangles and may invalidate offsets.
        Dim meshLod = TryCast(_tri, BSMeshLODTriShape)
        Dim subIndex = TryCast(_tri, BSSubIndexTriShape)
        Dim oldSegments As List(Of BSGeometrySegmentData) = Nothing
        If subIndex IsNot Nothing AndAlso subIndex.Segments IsNot Nothing Then
            oldSegments = subIndex.Segments.ToList()
        End If

        _tri.SetTriangles(Version, triangles)
        SyncDynamicIfNeeded()

        ' Redistribute count-derived metadata when caller provided provenance.  Without
        ' provenance the metadata stays as-is (likely stale — caller's responsibility).
        If provenance Is Nothing Then Return

        ' ─── BSMeshLODTriShape: lossy collapse to LOD2 ───
        ' Matches BodySlide-and-Outfit-Studio Geometry.cpp:1522 BSMeshLODTriShape::
        ' notifyVerticesDelete (lodSize0=lodSize1=0; lodSize2=numTriangles).  This is the
        ' canonical behaviour — even nifly itself doesn't try to be smart about LOD
        ' redistribution because the LOD bucket of a triangle isn't recoverable from a
        ' triangle-level provenance map (we'd need a triangle reorder pass too).  Lossy is
        ' OK because LOD2 is "always rendered at all distances" so no triangles disappear
        ' visually — only the LOD optimization is lost.
        If meshLod IsNot Nothing Then
            ' DEBUGGER.BREAK: TO TEST — first time this path executes, step through and
            ' verify lodSize2 equals new triangle count post-write.  Remove this line after
            ' validating with a real BSMeshLODTriShape NIF (rare in BodySlide outfits;
            ' common in distant-LOD meshes).  See memory: pending_tests_shape_metadata.md
            Debugger.Break()
            meshLod.LOD0Size = 0UI
            meshLod.LOD1Size = 0UI
            meshLod.LOD2Size = CUInt(triangles.Count)
            Return
        End If

        ' ─── BSSubIndexTriShape: full Segments + SubSegmentDatas redistribution ───
        If subIndex IsNot Nothing AndAlso oldSegments IsNot Nothing AndAlso oldSegments.Count > 0 Then
            ' DEBUGGER.BREAK: TO TEST — first time this path executes, step through and
            ' verify Segments[].StartIndex/NumPrimitives + SubSegment[].StartIndex/
            ' NumPrimitives are consistent and cover the new triangle list correctly.
            ' Remove after validation against an FO4 outfit with subindex + zap slider.
            ' See memory: pending_tests_shape_metadata.md
            Debugger.Break()
            Dim newSegments = RedistributeSegments(oldSegments, provenance, triangles.Count)
            subIndex.Segments = newSegments
            ' Align the parallel _segmentData (SSF + PerSegmentData records) so the NIF
            ' block stays internally consistent.  Our redistribute preserves segment AND
            ' sub-segment counts, but SegmentStarts (list of per-segment StartIndex in
            ' vertex-index units) and NumSegments / TotalSegments fields need refresh.
            AlignSubIndexSegmentData(subIndex, newSegments)
        End If
    End Sub

    ''' <summary>
    ''' Keeps BSSubIndexTriShape._segmentData (BSGeometrySegmentSharedData) consistent with
    ''' _segment after a triangle-count change.  Preserves SSFFile and PerSegmentData
    ''' records (material / userSlotID per segment+subsegment) because those reference
    ''' semantic identity that survives triangle compaction.  Only count-derived fields are
    ''' refreshed:
    '''   - NumSegments = parent segment count
    '''   - TotalSegments = parent count + sum of sub-segment counts (matches
    '''     PerSegmentData list size, which we don't resize because count stays stable
    '''     when redistribute preserves structure)
    '''   - SegmentStarts[i] = newSegments[i].StartIndex (per-parent starts)
    '''
    ''' Protection against structural drift: throws if our preserved count doesn't match
    ''' the existing PerSegmentData size — that would indicate a latent bug where
    ''' redistribute lost a sub-segment.
    ''' </summary>
    Private Shared Sub AlignSubIndexSegmentData(subIndex As BSSubIndexTriShape, newSegments As List(Of BSGeometrySegmentData))
        ' BSGeometrySegmentSharedData is a value struct on BSSubIndexTriShape.SegmentData.
        ' VB.NET won't let us mutate struct fields through a property-read, so we need to
        ' access via reflection to get the field ref (similar pattern to SetSkinning's
        ' NiSkinData.BoneList struct mutation via write-back).
        Dim sdField = SubIndexSegmentDataField
        If sdField Is Nothing Then
            Throw New InvalidOperationException(
                "BSSubIndexTriShape._segmentData reflection field lookup failed.  NiflySharp " &
                "internal field name may have changed — update SubIndexSegmentDataField accordingly.")
        End If
        Dim sd As BSGeometrySegmentSharedData = CType(sdField.GetValue(subIndex), BSGeometrySegmentSharedData)

        Dim totalSubSegments As UInteger = 0
        Dim starts As New List(Of UInteger)(newSegments.Count)
        For Each seg In newSegments
            starts.Add(seg.StartIndex)
            totalSubSegments += CUInt(If(seg.SubSegment Is Nothing, 0, seg.SubSegment.Count))
        Next
        Dim newTotal As UInteger = CUInt(newSegments.Count) + totalSubSegments

        ' Guard against PerSegmentData size drift.  Redistribute preserves count, so if the
        ' existing PerSegmentData size already differed from the computed total, something
        ' else mutated the shape first and we'd mask the inconsistency by overwriting.
        If sd.PerSegmentData IsNot Nothing AndAlso
           sd.TotalSegments <> 0 AndAlso
           sd.PerSegmentData.Count <> CInt(sd.TotalSegments) Then
            Throw New InvalidOperationException(
                $"BSSubIndexTriShape.SegmentData.PerSegmentData count ({sd.PerSegmentData.Count}) " &
                $"doesn't match SegmentData.TotalSegments ({sd.TotalSegments}) BEFORE redistribute.  " &
                "Shape is already structurally corrupt; refusing to mutate further.")
        End If

        sd.NumSegments = CUInt(newSegments.Count)
        sd.TotalSegments = newTotal
        sd.SegmentStarts = starts
        ' PerSegmentData preserved intact — count should be unchanged because redistribute
        ' preserves sub-segment counts.  SSFFile preserved intact — SSF data file reference
        ' is independent of triangle counts.

        sdField.SetValue(subIndex, sd)
    End Sub

    ''' <summary>
    ''' Reflection field accessor for BSSubIndexTriShape._segmentData (protected, no public
    ''' accessor in auto-gen).  Null if NiflySharp renames the field — AlignSubIndexSegmentData
    ''' throws explicitly in that case instead of NRE.
    ''' </summary>
    ' Public visibility so ShapeTypeValidator (in Wardrobe_Manager, different assembly) can
    ' reuse this reflection helper for round-trip comparisons — single source of truth.
    Public Shared ReadOnly SubIndexSegmentDataField As Reflection.FieldInfo =
        GetType(BSSubIndexTriShape).GetField("_segmentData",
                                             Reflection.BindingFlags.NonPublic Or Reflection.BindingFlags.Instance)

    ''' <summary>
    ''' NiflySharp BSTriShape bug workaround (ShapeTypeValidator test A regression discovered
    ''' 2026-04-20): when an SSE-skinned BSTriShape is serialized, <c>BSTriShape.BeforeSync</c>
    ''' ([BSTriShape.cs:72-79](NiflySharp/NiflySharp/Blocks/BSTriShape.cs#L72)) sets
    ''' <c>_numVertices = 0</c> because the vertex data is stored in NiSkinPartition instead of
    ''' in the block itself.  NiflySharp writes that zero to disk but never restores it after
    ''' save.  Subsequent load sees <c>_numVertices=0</c> on disk while the in-memory
    ''' <c>_vertexData_List_BSVDSSE</c> is reconstructed from the partition (real count).
    '''
    ''' Result: <c>VertexCount</c> property (which reads list.Count) returns the real count,
    ''' but <c>UpdateRawNormals/UVs/VertexColors/VertexPositions/Tangents/Bitangents</c> all
    ''' use the stale <c>_numVertices</c> field and return empty lists.  This silently breaks
    ''' the renderer (bounds calc gets Vector3(MaxValue) sentinel → scene size=-Infinity →
    ''' nearZ=Infinity → Matrix4.CreatePerspectiveFieldOfView throws).
    '''
    ''' Fix: before any read that goes through the UpdateRaw* path, reflection-sync
    ''' <c>_numVertices</c> with <c>VertexCount</c> (list.Count).  Non-destructive (no-op if
    ''' already in sync).  Consistent with the existing reflection precedent for
    ''' _segmentData / triParts (NiflySharp fields we need but aren't publicly exposed).
    ''' </summary>
    Private Shared ReadOnly NumVerticesField As Reflection.FieldInfo =
        GetType(BSTriShape).GetField("_numVertices",
                                      Reflection.BindingFlags.NonPublic Or Reflection.BindingFlags.Instance)

    ''' <summary>
    ''' Ensures <c>_numVertices</c> matches the actual packed-vertex list count.  Idempotent
    ''' — no-op when already in sync.  Must be called before any getter that routes through
    ''' NiflySharp's <c>UpdateRaw*</c> methods (VertexPositions / Normals / UVs /
    ''' VertexColors / Tangents / Bitangents) because those methods use the field, not the
    ''' list.
    ''' </summary>
    Private Sub EnsureNumVerticesSynced()
        If NumVerticesField Is Nothing Then Return
        Dim listCount As Integer = _tri.VertexCount  ' reads list.Count (see BSTriShape.cs:315)
        Dim fieldVal As UShort = CUShort(NumVerticesField.GetValue(_tri))
        If listCount > 0 AndAlso CInt(fieldVal) <> listCount Then
            NumVerticesField.SetValue(_tri, CUShort(listCount))
        End If
    End Sub

    ''' <summary>
    ''' Rebuilds a BSGeometrySegmentData list after a triangle-count change.  For each
    ''' old segment, counts how many new triangles came from its [StartIndex/3,
    ''' StartIndex/3 + NumPrimitives) range using <paramref name="provenance"/>.  Realigns
    ''' the StartIndex of each new segment to be cumulative (previous.StartIndex +
    ''' previous.NumPrimitives * 3) — same convention BS-OS uses (Geometry.cpp:1289).
    ''' SubSegmentDatas within each segment get the same treatment recursively.
    '''
    ''' Triangle-order assumption: this algorithm assumes that the new triangle list
    ''' preserves the relative order of triangles within each old segment (i.e. survivors
    ''' from old segment N still come before survivors from old segment N+1).  Zap and
    ''' split satisfy this trivially (filter preserves order).  Merge populates segments
    ''' via append rather than this algorithm so the assumption isn't tested there.
    ''' </summary>
    ''' <summary>
    ''' Friend visibility: NiTriShapeGeometry.BSSegmentedTriShape branch reuses this exact
    ''' redistribution logic (BSSegmented uses the same BSGeometrySegmentData struct, just
    ''' on a different host class).  Keeping a single implementation avoids drift between
    ''' the two shape families.
    ''' </summary>
    Friend Shared Function RedistributeSegments(oldSegments As List(Of BSGeometrySegmentData),
                                                  provenance As TriangleRemap,
                                                  newTriCount As Integer) As List(Of BSGeometrySegmentData)
        Dim result As New List(Of BSGeometrySegmentData)(oldSegments.Count)
        Dim cumulativeTriIdx As Integer = 0
        ' Track new triangles NOT covered by any old segment (cross-shape entries from
        ' merge, or synthetic triangles with oldIdx=-1).  Emitted as a final "catch-all"
        ' segment so dismember engine doesn't read out of bounds.
        Dim coveredNewIndices As New HashSet(Of Integer)()

        For Each oldSeg In oldSegments
            Dim oldStartTri As Integer = CInt(oldSeg.StartIndex \ 3UI)
            Dim oldEndTri As Integer = oldStartTri + CInt(oldSeg.NumPrimitives)

            ' Count survivors from this old segment: new triangles whose source falls in range.
            Dim survivors As Integer = 0
            For newIdx = 0 To provenance.Sources.Count - 1
                Dim src = provenance.Sources(newIdx)
                ' Skip cross-shape provenance for redistribution (merge case — handled
                ' by fallback segment below + MergeMetadataAfterApply append) and synthetic
                ' triangles (oldIdx = -1, covered by fallback).
                If src.Shape IsNot Nothing OrElse src.OldIdx < 0 Then Continue For
                If src.OldIdx >= oldStartTri AndAlso src.OldIdx < oldEndTri Then
                    survivors += 1
                    coveredNewIndices.Add(newIdx)
                End If
            Next

            Dim newSeg As New BSGeometrySegmentData() With {
                .Flags = oldSeg.Flags,
                .StartIndex = CUInt(cumulativeTriIdx) * 3UI,
                .NumPrimitives = CUInt(survivors),
                .ParentArrayIndex = oldSeg.ParentArrayIndex
            }

            ' SubSegments: same algorithm, scoped to the parent segment range.  Realigned
            ' cumulatively starting from the new parent's StartIndex.
            If oldSeg.SubSegment IsNot Nothing AndAlso oldSeg.SubSegment.Count > 0 Then
                newSeg.SubSegment = RedistributeSubSegments(oldSeg.SubSegment, provenance, CInt(newSeg.StartIndex \ 3UI))
                newSeg.NumSubSegments = CUInt(newSeg.SubSegment.Count)
            Else
                newSeg.SubSegment = New List(Of BSGeometrySubSegment)()
                newSeg.NumSubSegments = 0UI
            End If

            result.Add(newSeg)
            cumulativeTriIdx += survivors
        Next

        ' Runtime validation (was Debug.Assert — upgraded to hard throw so release builds
        ' also catch malformed provenance before the NIF gets written with inconsistent
        ' segment ranges that would make the game read out-of-bounds triangles).
        If cumulativeTriIdx > newTriCount Then
            Throw New InvalidOperationException(
                $"RedistributeSegments: cumulative survivors ({cumulativeTriIdx}) exceeds new triangle " &
                $"count ({newTriCount}).  Provenance map is malformed (duplicate oldIdx entries or " &
                "oldIdx values outside original triangle range).  Refusing to produce a segmented NIF " &
                "that would be read out-of-bounds by the dismember engine.")
        End If

        ' Synthetic-only fallback: new triangles with (Shape=Nothing AND OldIdx<0) are
        ' synthetic entries in same-shape provenance (e.g. a future caller that appends
        ' generated triangles to an existing shape).  Bundle those — and ONLY those — into
        ' a catch-all segment so the shape stays dismember-legal.
        '
        ' Cross-shape entries (Shape IsNot Nothing, from merge) are NOT covered here:
        ' MergeShapesHelper.MergeMetadataAfterApply is responsible for appending donor
        ' segments with proper StartIndex offset.  Emitting a fallback AND appending donor
        ' segments would double-count those triangles (PrimSum > TC — a dismember-illegal
        ' NIF that was discovered by ShapeTypeValidator test C).
        Dim syntheticUncovered As Integer = 0
        For newIdx = 0 To provenance.Sources.Count - 1
            If coveredNewIndices.Contains(newIdx) Then Continue For
            Dim src = provenance.Sources(newIdx)
            If src.Shape Is Nothing AndAlso src.OldIdx < 0 Then
                syntheticUncovered += 1
            End If
        Next

        If syntheticUncovered > 0 AndAlso cumulativeTriIdx + syntheticUncovered <= newTriCount Then
            Dim fallback As New BSGeometrySegmentData() With {
                .Flags = 0,
                .StartIndex = CUInt(cumulativeTriIdx) * 3UI,
                .NumPrimitives = CUInt(syntheticUncovered),
                .ParentArrayIndex = UInteger.MaxValue,  ' "no parent" sentinel (matches BS-OS SetDefaultSegments convention)
                .NumSubSegments = 0UI,
                .SubSegment = New List(Of BSGeometrySubSegment)()
            }
            result.Add(fallback)
        End If

        Return result
    End Function

    ''' <summary>
    ''' Same redistribution algorithm as <see cref="RedistributeSegments"/> but for the
    ''' sub-segment list of a single parent segment.  StartIndex of each new sub-segment is
    ''' cumulative starting from <paramref name="newParentStartTri"/> (in triangle units —
    ''' multiplied by 3 for storage as vertex-index units).
    ''' </summary>
    Private Shared Function RedistributeSubSegments(oldSubSegments As List(Of BSGeometrySubSegment),
                                                     provenance As TriangleRemap,
                                                     newParentStartTri As Integer) As List(Of BSGeometrySubSegment)
        Dim result As New List(Of BSGeometrySubSegment)(oldSubSegments.Count)
        Dim cumulativeTriIdx As Integer = newParentStartTri

        For Each oldSub In oldSubSegments
            Dim oldStartTri As Integer = CInt(oldSub.StartIndex \ 3UI)
            Dim oldEndTri As Integer = oldStartTri + CInt(oldSub.NumPrimitives)

            Dim survivors As Integer = 0
            For newIdx = 0 To provenance.Sources.Count - 1
                Dim src = provenance.Sources(newIdx)
                If src.Shape IsNot Nothing OrElse src.OldIdx < 0 Then Continue For
                If src.OldIdx >= oldStartTri AndAlso src.OldIdx < oldEndTri Then survivors += 1
            Next

            result.Add(New BSGeometrySubSegment() With {
                .StartIndex = CUInt(cumulativeTriIdx) * 3UI,
                .NumPrimitives = CUInt(survivors),
                .ParentArrayIndex = oldSub.ParentArrayIndex,
                .Unused = oldSub.Unused
            })
            cumulativeTriIdx += survivors
        Next

        Return result
    End Function

    Public Sub UpdateBounds() Implements IShapeGeometry.UpdateBounds
        _tri.UpdateBounds()
    End Sub

    ''' <summary>
    ''' Writes per-vertex bone influences into BSVertexData[].BoneIndices / BoneWeights
    ''' (FO4) or BSVertexDataSSE[].BoneIndices / BoneWeights (SSE).  Length of the packed
    ''' list and <paramref name="skinning"/>.VertexCount must match.  Each vertex's 4 slots
    ''' are written in order; missing slots in the input default to (idx=0, weight=0).
    ''' </summary>
    Public Sub SetSkinning(skinning As ShapeSkinningData) Implements IShapeGeometry.SetSkinning
        If skinning.BoneIndices Is Nothing OrElse skinning.BoneWeights Is Nothing Then Return
        Dim n As Integer = _tri.VertexCount
        If skinning.VertexCount <> n Then
            Debug.Assert(False, $"SetSkinning vertex count mismatch: shape has {n}, skinning has {skinning.VertexCount}")
            Return
        End If
        Const wpv As Integer = 4
        Dim inputWpv As Integer = If(skinning.WeightsPerVertex > 0, skinning.WeightsPerVertex, wpv)

        If Version.IsSSE Then
            Dim vd = _tri.VertexDataSSE
            If vd Is Nothing OrElse vd.Count <> n Then Return
            For i = 0 To n - 1
                Dim v = vd(i)   ' struct copy (BSVertexDataSSE is a struct)
                Dim newIdx(wpv - 1) As Byte
                Dim newWgt(wpv - 1) As SysHalf
                Dim copy As Integer = Math.Min(wpv, inputWpv)
                For j = 0 To copy - 1
                    newIdx(j) = skinning.BoneIndices(i * inputWpv + j)
                    newWgt(j) = skinning.BoneWeights(i * inputWpv + j)
                Next
                v.BoneIndices = newIdx
                v.BoneWeights = newWgt
                vd(i) = v   ' write back the modified struct
            Next
        Else
            Dim vd = _tri.VertexData
            If vd Is Nothing OrElse vd.Count <> n Then Return
            For i = 0 To n - 1
                Dim v = vd(i)
                Dim newIdx(wpv - 1) As Byte
                Dim newWgt(wpv - 1) As SysHalf
                Dim copy As Integer = Math.Min(wpv, inputWpv)
                For j = 0 To copy - 1
                    newIdx(j) = skinning.BoneIndices(i * inputWpv + j)
                    newWgt(j) = skinning.BoneWeights(i * inputWpv + j)
                Next
                v.BoneIndices = newIdx
                v.BoneWeights = newWgt
                vd(i) = v
            Next
        End If
        ' BSDynamicTriShape safety: CalcDynamicData() re-syncs the parallel Vector4 _vertices
        ' buffer (carries BitangentX in W).  SetSkinning only mutates BoneIndices/BoneWeights,
        ' which don't affect _vertices, but call SyncDynamicIfNeeded defensively so every
        ' write path on BSTriShapeGeometry leaves the dynamic buffer coherent.
        SyncDynamicIfNeeded()
    End Sub

    ' ─────────────── Helpers ───────────────
    Private Shared Function DecodeBitangent(x As Single, by As SByte, bz As SByte) As SysNumerics.Vector3
        Dim yf As Single = (CInt(by) And &HFF) / 255.0F * 2.0F - 1.0F
        Dim zf As Single = (CInt(bz) And &HFF) / 255.0F * 2.0F - 1.0F
        Return NormalizeOrZero(New SysNumerics.Vector3(x, yf, zf))
    End Function

    Private Shared Function DecodeByteVector3(x As SByte, y As SByte, z As SByte) As SysNumerics.Vector3
        Dim xf As Single = (CInt(x) And &HFF) / 255.0F * 2.0F - 1.0F
        Dim yf As Single = (CInt(y) And &HFF) / 255.0F * 2.0F - 1.0F
        Dim zf As Single = (CInt(z) And &HFF) / 255.0F * 2.0F - 1.0F
        Return New SysNumerics.Vector3(xf, yf, zf)
    End Function

    Private Shared Function NormalizeOrZero(v As SysNumerics.Vector3) As SysNumerics.Vector3
        Dim len As Single = v.Length()
        If len > 0.000001F Then Return v / len
        Return SysNumerics.Vector3.Zero
    End Function

    ''' <summary>
    ''' BSDynamicTriShape carries a parallel List(Of Vector4) Vertices field (XYZ position + W
    ''' carrying BitangentX) that is read at runtime by the cloth/dynamic system.  After any
    ''' mutation of the inline BSVertexData positions, that parallel buffer must be re-synced
    ''' via CalcDynamicData() — otherwise the saved NIF carries stale dynamic data even though
    ''' the static positions are correct.  No-op for plain BSTriShape and other subclasses.
    ''' </summary>
    Private Sub SyncDynamicIfNeeded()
        Dim dyn = TryCast(_tri, BSDynamicTriShape)
        If dyn IsNot Nothing Then dyn.CalcDynamicData()
    End Sub

    ''' <summary>
    ''' Copies up to <paramref name="wpv"/> bone influence slots from a single BSVertexData
    ''' vertex into the flat output arrays at vertex offset <paramref name="vIdx"/>.  Pads
    ''' missing slots with index=0, weight=0 — same convention as ShapeSkinningData.Empty.
    ''' </summary>
    Private Shared Sub CopyVertexInfluences(srcIdx As Byte(), srcWgt As SysHalf(), outIdx As Byte(), outWgt As SysHalf(), vIdx As Integer, wpv As Integer)
        Dim base As Integer = vIdx * wpv
        Dim haveIdx As Integer = If(srcIdx Is Nothing, 0, srcIdx.Length)
        Dim haveWgt As Integer = If(srcWgt Is Nothing, 0, srcWgt.Length)
        Dim copy As Integer = Math.Min(wpv, Math.Min(haveIdx, haveWgt))
        For j = 0 To copy - 1
            outIdx(base + j) = srcIdx(j)
            outWgt(base + j) = srcWgt(j)
        Next
        ' Remaining slots already default to 0 via Dim allocation.
    End Sub

    ''' <summary>
    ''' Reads the bone-palette block indices from the shape's skin instance Bones reference list.
    ''' Returns an empty array when the skin instance is missing or has no bones.  Pure
    ''' diagnostics — the renderer does not consume this; ShapeBones on IRenderableShape is the
    ''' authoritative source for matrices.
    ''' </summary>
    Private Function ResolveBonePalette() As Integer()
        If _tri.SkinInstanceRef Is Nothing OrElse _tri.SkinInstanceRef.Index = -1 Then Return Array.Empty(Of Integer)()
        If _tri.SkinInstanceRef.Index >= _nif.Blocks.Count Then Return Array.Empty(Of Integer)()
        Dim skinInst = TryCast(_nif.Blocks(_tri.SkinInstanceRef.Index), INiSkin)
        If skinInst Is Nothing OrElse skinInst.Bones Is Nothing Then Return Array.Empty(Of Integer)()
        Return skinInst.Bones.Indices.Select(Function(i) CInt(i)).ToArray()
    End Function
End Class
